import {appConfig} from "../config";

export const API_ENDPOINT = appConfig.API_URL;

export const GET_HOME_API = "web/home";
export const GET_HOME_SUCCESS = "GET_HOME_SUCCESS";
export const GET_HOME_ERROR = "GET_HOME_ERROR";

export const POST_API_MASTER_SUCCESS = "POST_API_MASTER_SUCCESS";
export const POST_API_MASTER_ERROR = "POST_API_MASTER_ERROR";
export const PUT_API_MASTER_SUCCESS = "PUT_API_MASTER_SUCCESS";
export const PUT_API_MASTER_ERROR = "PUT_API_MASTER_ERROR";

export const GET_COLLEGE_MASTER_API = "/college";
export const PUT_COLLEGE_MASTER_SUCCESS = "PUT_COLLEGE_MASTER_SUCCESS";
export const PUT_COLLEGE_MASTER_ERROR = "PUT_COLLEGE_MASTER_ERROR";
export const POST_COLLEGE_MASTER_SUCCESS = "POST_COLLEGE_MASTER_SUCCESS";
export const POST_COLLEGE_MASTER_ERROR = "POST_COLLEGE_MASTER_ERROR";
export const GET_COLLEGE_MASTER_SUCCESS = "GET_COLLEGE_MASTER_SUCCESS";
export const GET_COLLEGE_MASTER_ERROR = "GET_COLLEGE_MASTER_ERROR";
export const EXPORT_COLLEGE_MASTER_API = "/college-export";
export const EXPORT_COLLEGE_MASTER_ALLDATA_API = "/college-export-all";
export const IMPORT_COLLEGE_MASTER_API = "/college-import";

export const GET_ACCOMODATION_API = "/accomodation";
export const EXPORT_ACCOMODATION_ALLDATA_API = "/accomodation-export-all";
export const EXPORT_ACCOMODATION_API = "/accomodation-export";
export const IMPORT_ACCOMODATION_API = "/accomodation-import";
export const GET_ACCOMODATION_SUCCESS = "GET_ACCOMODATION_SUCCESS";
export const GET_ACCOMODATION_ERROR = "GET_ACCOMODATION_ERROR";
export const GET_ACCOMODATION_TYPE_LIST = "/accomodation-type-list";
export const GET_ACCOMODATION_TYPE_LIST_SUCCESS = "GET_ACCOMODATION_TYPE_LIST_SUCCESS";
export const GET_ACCOMODATION_TYPE_LIST_ERROR = "GET_ACCOMODATION_TYPE_LIST_ERROR";
export const GET_ACCOMODATION_TYPE = "/accomodation-type";
export const GET_ACCOMODATION_TYPE_SUCCESS = "GET_ACCOMODATION_TYPE_SUCCESS";
export const GET_ACCOMODATION_TYPE_ERROR = "GET_ACCOMODATION_TYPE_ERROR";
export const POST_ACCOMODATION_ERROR = "POST_ACCOMODATION_ERROR";
export const POST_ACCOMODATION_SUCCESS = "POST_ACCOMODATION_SUCCESS";
export const PUT_ACCOMODATION_SUCCESS = "PUT_ACCOMODATION_SUCCESS";
export const PUT_ACCOMODATION_ERROR = "PUT_ACCOMODATION_ERROR";

export const GET_COURSE_FAQ_API = "/course-faq";
export const GET_COURSE_FAQ_SUCCESS = "GET_COURSE_FAQ_SUCCESS";
export const GET_COURSE_FAQ_ERROR = "GET_COURSE_FAQ_ERROR";
export const EXPORT_COURSE_FAQ_ALLDATA_API = "/course-faq-export-all";
export const EXPORT_COURSE_FAQ_API = "/course-faq-export";
export const IMPORT_COURSE_FAQ_API = "/course-faq-import";
export const POST_COURSE_FAQ_ERROR = "POST_COURSE_FAQ_ERROR";
export const POST_COURSE_FAQ_SUCCESS = "POST_COURSE_FAQ_SUCCESS";
export const PUT_COURSE_FAQ_SUCCESS = "PUT_COURSE_FAQ_SUCCESS";
export const PUT_COURSE_FAQ_ERROR = "PUT_COURSE_FAQ_ERROR";

export const GET_COURSE_LIST_API = "/course-list";
export const GET_COURSE_LIST_SUCCESS = "GET_COURSE_LIST_SUCCESS";
export const GET_COURSE_LIST_ERROR = "GET_COURSE_LIST_ERROR";

export const GET_COURSE_ASSET_API = "/course-asset";
export const GET_COURSE_ASSET_SUCCESS = "GET_COURSE_ASSET_SUCCESS";
export const GET_COURSE_ASSET_ERROR = "GET_COURSE_ASSET_ERROR";
export const EXPORT_COURSE_ASSET_ALLDATA_API = "/course-asset-export-all";
export const EXPORT_COURSE_ASSET_API = "/course-asset-export";
export const IMPORT_COURSE_ASSET_API = "/course-asset-import";
export const POST_COURSE_ASSET_SUCCESS = "POST_COURSE_ASSET_SUCCESS";
export const POST_COURSE_ASSET_ERROR = "POST_COURSE_ASSET_ERROR";
export const PUT_COURSE_ASSET_SUCCESS = "PUT_COURSE_ASSET_SUCCESS";
export const PUT_COURSE_ASSET_ERROR = "PUT_COURSE_ASSET_ERROR";

export const GET_CONTENT_TYPE_API = "/contenttype";
export const GET_CONTENT_TYPE_SUCCESS = "GET_CONTENT_TYPE_SUCCESS";
export const GET_CONTENT_TYPE_ERROR = "GET_CONTENT_TYPE_ERROR";
export const GET_CONTENT_TYPE_LIST_API = "/contenttype-list";
export const GET_CONTENT_TYPE_LIST_SUCCESS = "GET_CONTENT_TYPE_LIST_SUCCESS";
export const GET_CONTENT_TYPE_LIST_ERROR = "GET_CONTENT_TYPE_LIST_ERROR";
export const EXPORT_CONTENT_TYPE_ALLDATA_API = "/contenttype-export-all";
export const EXPORT_CONTENT_TYPE_API = "/contenttype-export";
export const IMPORT_CONTENT_TYPE_API = "/contenttype-import";
export const POST_CONTENT_TYPE_SUCCESS = "POST_CONTENT_TYPE_SUCCESS";
export const POST_CONTENT_TYPE_ERROR = "POST_CONTENT_TYPE_ERROR";
export const PUT_CONTENT_TYPE_SUCCESS = "PUT_CONTENT_TYPE_SUCCESS";
export const PUT_CONTENT_TYPE_ERROR = "PUT_CONTENT_TYPE_ERROR";

export const GET_COURSE_MASTER_API = "/career-course";
export const GET_COURSE_MASTER_SUCCESS = "GET_COURSE_MASTER_SUCCESS";
export const GET_COURSE_MASTER_ERROR = "GET_COURSE_MASTER_ERROR";
export const GET_COURSE_MASTER_LIST_API = "/career-course-list";
export const GET_COURSE_MASTER_LIST_SUCCESS = "GET_COURSE_MASTER_LIST_SUCCESS";
export const GET_COURSE_MASTER_LIST_ERROR = "GET_COURSE_MASTER_LIST_ERROR";
export const EXPORT_COURSE_MASTER_ALLDATA_API = "/career-course-export-all";
export const EXPORT_COURSE_MASTER_API = "/career-course-export";
export const IMPORT_COURSE_MASTER_API = "/career-course-import";
export const POST_COURSE_MASTER_SUCCESS = "POST_COURSE_MASTER_SUCCESS";
export const POST_COURSE_MASTER_ERROR = "POST_COURSE_MASTER_ERROR";
export const PUT_COURSE_MASTER_SUCCESS = "PUT_COURSE_MASTER_SUCCESS";
export const PUT_COURSE_MASTER_ERROR = "PUT_COURSE_MASTER_ERROR";

export const GET_CATAGORY_API = "/category";
export const GET_CATAGORY_SUCCESS = "GET_CATAGORY_SUCCESS";
export const GET_CATAGORY_ERROR = "GET_CATAGORY_ERROR";
export const EXPORT_CATAGORY_ALLDATA_API = "/category-export-all";
export const EXPORT_CATAGORY_API = "/category-export";
export const IMPORT_CATAGORY_API = "/category-import";
export const POST_CATAGORY_SUCCESS = "POST_CATAGORY_SUCCESS";
export const POST_CATAGORY_ERROR = "POST_CATAGORY_ERROR";
export const PUT_CATAGORY_SUCCESS = "PUT_CATAGORY_SUCCESS";
export const PUT_CATAGORY_ERROR = "PUT_CATAGORY_ERROR";

export const GET_COURSE_SECTION_API = "/course-section";
export const GET_COURSE_SECTION_SUCCESS = "GET_COURSE_SECTION_SUCCESS";
export const GET_COURSE_SECTION_ERROR = "GET_COURSE_SECTION_ERROR";
export const GET_COURSE_SECTION_LIST_API = "/course-section-list";
export const GET_COURSE_SECTION_LIST_SUCCESS = "GET_COURSE_SECTION_LIST_SUCCESS";
export const GET_COURSE_SECTION_LIST_ERROR = "GET_COURSE_SECTION_LIST_ERROR";
export const EXPORT_COURSE_SECTION_ALLDATA_API = "/course-section-export-all";
export const EXPORT_COURSE_SECTION_API = "/course-section-export";
export const IMPORT_COURSE_SECTION_API = "/course-section-import";
export const POST_COURSE_SECTION_SUCCESS = "POST_COURSE_SECTION_SUCCESS";
export const POST_COURSE_SECTION_ERROR = "POST_COURSE_SECTION_ERROR";
export const PUT_COURSE_SECTION_SUCCESS = "PUT_COURSE_SECTION_SUCCESS";
export const PUT_COURSE_SECTION_ERROR = "PUT_COURSE_SECTION_ERROR";

export const GET_COUNTRY_API = "/country";
export const GET_COUNTRY_SUCCESS = "GET_COUNTRY_SUCCESS";
export const GET_COUNTRY_ERROR = "GET_COUNTRY_ERROR";
export const GET_COUNTRY_LIST_API = "/country-list";
export const GET_COUNTRY_LIST_SUCCESS = "GET_COUNTRY_LIST_SUCCESS";
export const GET_COUNTRY_LIST_ERROR = "GET_COUNTRY_LIST_ERROR";
export const EXPORT_COUNTRY_ALLDATA_API = "/country-export-all";
export const EXPORT_COUNTRY_API = "/country-export";
export const IMPORT_COUNTRY_API = "/country-import";
export const POST_COUNTRY_SUCCESS = "POST_COUNTRY_SUCCESS";
export const POST_COUNTRY_ERROR = "POST_COUNTRY_ERROR";
export const PUT_COUNTRY_SUCCESS = "PUT_COUNTRY_SUCCESS";
export const PUT_COUNTRY_ERROR = "PUT_COUNTRY_ERROR";

export const GET_REGIONAL_OCCUPATION_API = "/occupation-master";
export const GET_REGIONAL_OCCUPATION_SUCCESS = "GET_REGIONAL_OCCUPATION_SUCCESS";
export const GET_REGIONAL_OCCUPATION_ERROR = "GET_REGIONAL_OCCUPATION_ERROR";
export const GET_REGIONAL_OCCUPATION_LIST_API = "/occupation-master-list";
export const GET_REGIONAL_OCCUPATION_LIST_SUCCESS = "GET_REGIONAL_OCCUPATION_LIST_SUCCESS";
export const GET_REGIONAL_OCCUPATION_LIST_ERROR = "GET_REGIONAL_OCCUPATION_LIST_ERROR";
export const EXPORT_REGIONAL_OCCUPATION_ALLDATA_API = "/occupation-master-export-all";
export const EXPORT_REGIONAL_OCCUPATION_API = "/occupation-master-export";
export const IMPORT_REGIONAL_OCCUPATION_API = "/occupation-master-import";
export const POST_REGIONAL_OCCUPATION_SUCCESS = "POST_REGIONAL_OCCUPATION_SUCCESS";
export const POST_REGIONAL_OCCUPATION_ERROR = "POST_REGIONAL_OCCUPATION_ERROR";
export const PUT_REGIONAL_OCCUPATION_SUCCESS = "PUT_REGIONAL_OCCUPATION_SUCCESS";
export const PUT_REGIONAL_OCCUPATION_ERROR = "PUT_REGIONAL_OCCUPATION_ERROR";

export const GET_OCCUPATION_QUALIFICATION_API = "/occupation-qualification";
export const GET_OCCUPATION_QUALIFICATION_SUCCESS = "GET_OCCUPATION_QUALIFICATION_SUCCESS";
export const GET_OCCUPATION_QUALIFICATION_ERROR = "GET_OCCUPATION_QUALIFICATION_ERROR";
export const GET_OCCUPATION_QUALIFICATION_LIST_SUCCESS = "GET_OCCUPATION_QUALIFICATION_LIST_SUCCESS";
export const GET_OCCUPATION_QUALIFICATION_LIST_ERROR = "GET_OCCUPATION_QUALIFICATION_LIST_ERROR";
export const EXPORT_OCCUPATION_QUALIFICATION_ALLDATA_API = "/occupation-qualification-export-all";
export const EXPORT_OCCUPATION_QUALIFICATION_API = "/occupation-qualification-export";
export const IMPORT_OCCUPATION_QUALIFICATION_API = "/occupation-qualification-import";
export const POST_OCCUPATION_QUALIFICATION_SUCCESS = "POST_OCCUPATION_QUALIFICATION_SUCCESS";
export const POST_OCCUPATION_QUALIFICATION_ERROR = "POST_OCCUPATION_QUALIFICATION_ERROR";
export const PUT_OCCUPATION_QUALIFICATION_SUCCESS = "PUT_OCCUPATION_QUALIFICATION_SUCCESS";
export const PUT_OCCUPATION_QUALIFICATION_ERROR = "PUT_OCCUPATION_QUALIFICATION_ERROR";

export const GET_MASTER_EXAMINATION_API = "/examination-master";
export const GET_MASTER_EXAMINATION_SUCCESS = "GET_OCCUPATION_QUALIFICATION_SUCCESS";
export const GET_MASTER_EXAMINATION_ERROR = "GET_OCCUPATION_QUALIFICATION_ERROR";
export const GET_MASTER_EXAMINATION_LIST_SUCCESS = "GET_OCCUPATION_QUALIFICATION_LIST_SUCCESS";
export const GET_MASTER_EXAMINATION_LIST_ERROR = "GET_OCCUPATION_QUALIFICATION_LIST_ERROR";
export const EXPORT_MASTER_EXAMINATION_ALLDATA_API = "/examination-master-export-all";
export const EXPORT_MASTER_EXAMINATION_API = "/examination-master-export";
export const IMPORT_MASTER_EXAMINATION_API = "/examination-master-import";
export const POST_MASTER_EXAMINATION_SUCCESS = "POST_OCCUPATION_QUALIFICATION_SUCCESS";
export const POST_MASTER_EXAMINATION_ERROR = "POST_OCCUPATION_QUALIFICATION_ERROR";
export const PUT_MASTER_EXAMINATION_SUCCESS = "PUT_OCCUPATION_QUALIFICATION_SUCCESS";
export const PUT_MASTER_EXAMINATION_ERROR = "PUT_OCCUPATION_QUALIFICATION_ERROR";

export const GET_STUDY_ROUTE_PATH_API = "/occupation-studyroutepath";
export const GET_STUDY_ROUTE_PATH_SUCCESS = "GET_STUDY_ROUTE_PATH_SUCCESS";
export const GET_STUDY_ROUTE_PATH_ERROR = "GET_STUDY_ROUTE_PATH_ERROR";
export const GET_STUDY_ROUTE_PATH_LIST_API = "/occupation-studyroutepath-list";
export const GET_STUDY_ROUTE_PATH_LIST_SUCCESS = "GET_STUDY_ROUTE_PATH_LIST_SUCCESS";
export const GET_STUDY_ROUTE_PATH_LIST_ERROR = "GET_STUDY_ROUTE_PATH_LIST_ERROR";
export const EXPORT_STUDY_ROUTE_PATH_ALLDATA_API = "/occupation-studyroutepath-export-all";
export const EXPORT_STUDY_ROUTE_PATH_API = "/occupation-studyroutepath-export";
export const IMPORT_STUDY_ROUTE_PATH_API = "/occupation-studyroutepath-import";
export const POST_STUDY_ROUTE_PATH_SUCCESS = "POST_STUDY_ROUTE_PATH_SUCCESS";
export const POST_STUDY_ROUTE_PATH_ERROR = "POST_STUDY_ROUTE_PATH_ERROR";
export const PUT_STUDY_ROUTE_PATH_SUCCESS = "PUT_STUDY_ROUTE_PATH_SUCCESS";
export const PUT_STUDY_ROUTE_PATH_ERROR = "PUT_STUDY_ROUTE_PATH_ERROR";

export const GET_STUDY_ROUTE_API = "/study-route";
export const GET_STUDY_ROUTE_SUCCESS = "GET_STUDY_ROUTE_SUCCESS";
export const GET_STUDY_ROUTE_ERROR = "GET_STUDY_ROUTE_ERROR";
export const EXPORT_STUDY_ROUTE_ALLDATA_API = "/study-route-export-all";
export const EXPORT_STUDY_ROUTE_API = "/study-route-export";
export const IMPORT_STUDY_ROUTE_API = "/study-route-import";
export const POST_STUDY_ROUTE_SUCCESS = "POST_STUDY_ROUTE_SUCCESS";
export const POST_STUDY_ROUTE_ERROR = "POST_STUDY_ROUTE_ERROR";
export const PUT_STUDY_ROUTE_SUCCESS = "PUT_STUDY_ROUTE_SUCCESS";
export const PUT_STUDY_ROUTE_ERROR = "PUT_STUDY_ROUTE_ERROR";

export const GET_COURSE_DETAILS_API = "/course-details";
export const GET_COURSE_DETAILS_SUCCESS = "GET_COURSE_DETAILS_SUCCESS";
export const GET_COURSE_DETAILS_ERROR = "GET_COURSE_DETAILS_ERROR";
export const EXPORT_COURSE_DETAILS_ALLDATA_API = "/course-details-export-all";
export const EXPORT_COURSE_DETAILS_API = "/course-details-export";
export const IMPORT_COURSE_DETAILS_API = "/course-details-import";
export const POST_COURSE_DETAILS_ERROR = "POST_COURSE_DETAILS_ERROR";
export const POST_COURSE_DETAILS_SUCCESS = "POST_COURSE_DETAILS_SUCCESS";
export const PUT_COURSE_DETAILS_SUCCESS = "PUT_COURSE_DETAILS_SUCCESS";
export const PUT_COURSE_DETAILS_ERROR = "PUT_COURSE_DETAILS_ERROR";

export const GET_LANGUAGE_LIST = "/language-list";
export const GET_LANGUAGE_LIIST_SUCCESS = "GET_LANGUAGE_LIIST_SUCCESS";
export const GET_LANGUAGE_LIIST_ERROR = "GET_LANGUAGE_LIIST_ERROR";

export const GET_SKILL_LIST = "/skill-list";
export const GET_SKILL_LIST_SUCCESS = "GET_SKILL_LIST_SUCCESS";
export const GET_SKILL_LIST_ERROR = "GET_SKILL_LIST_ERROR";

export const GET_INTEREST_PATHWAY_LIST = "/interest-pathway-list";
export const GET_INTEREST_PATHWAY_LIST_SUCCESS = "GET_INTEREST_PATHWAY_LIST_SUCCESS";
export const GET_INTEREST_PATHWAY_LIST_ERROR = "GET_INTEREST_PATHWAY_LIST_ERROR";

export const GET_PUBLISHER_LIST = "/publisher-list";
export const GET_PUBLISHER_LIST_SUCCESS = "GET_PUBLISHER_LIST_SUCCESS";
export const GET_PUBLISHER_LIST_ERROR = "GET_PUBLISHER_LIST_ERROR";

export const GET_SECTION_CONTENT_API = "/section-content";
export const GET_SECTION_CONTENT_SUCCESS = "GET_SECTION_CONTENT_SUCCESS";
export const GET_SECTION_CONTENT_ERROR = "GET_SECTION_CONTENT_ERROR";
export const EXPORT_SECTION_CONTENT_ALLDATA_API = "/section-content-export-all";
export const EXPORT_SECTION_CONTENT_API = "/section-content-export";
export const IMPORT_SECTION_CONTENT_API = "/section-content-import";
export const POST_SECTION_CONTENT_ERROR = "POST_SECTION_CONTENT_ERROR";
export const POST_SECTION_CONTENT_SUCCESS = "POST_SECTION_CONTENT_SUCCESS";
export const PUT_SECTION_CONTENT_SUCCESS = "PUT_SECTION_CONTENT_SUCCESS";
export const PUT_SECTION_CONTENT_ERROR = "PUT_SECTION_CONTENT_ERROR";

export const GET_ACCREDIATION_MASTER_API = "/accrediation-master";
export const GET_ACCREDIATION_MASTER_SUCCESS = "GET_ACCREDIATION_MASTER_SUCCESS";
export const GET_ACCREDIATION_MASTER_ERROR = "GET_ACCREDIATION_MASTER_ERROR";
export const GET_ACCREDIATION_MASTER_LIST_API = "/accrediation-master-list";
export const GET_ACCREDIATION_MASTER_LIST_SUCCESS = "GET_ACCREDIATION_MASTER_LIST_SUCCESS";
export const GET_ACCREDIATION_MASTER_LIST_ERROR = "GET_ACCREDIATION_MASTER_LIST_ERROR";
export const EXPORT_ACCREDIATION_MASTER_ALLDATA_API = "/accrediation-master-export-all";
export const EXPORT_ACCREDIATION_MASTER_API = "/accrediation-master-export";
export const IMPORT_ACCREDIATION_MASTER_API = "/accrediation-master-import";
export const POST_ACCREDIATION_MASTER_SUCCESS = "POST_ACCREDIATION_MASTER_SUCCESS";
export const POST_ACCREDIATION_MASTER_ERROR = "POST_ACCREDIATION_MASTER_ERROR";
export const PUT_ACCREDIATION_MASTER_SUCCESS = "PUT_ACCREDIATION_MASTER_SUCCESS";
export const PUT_ACCREDIATION_MASTER_ERROR = "PUT_ACCREDIATION_MASTER_ERROR";

export const GET_AFFILIATION_MASTER_API = "/affiliation-master";
export const GET_AFFILIATION_MASTER_SUCCESS = "GET_AFFILIATION_MASTER_SUCCESS";
export const GET_AFFILIATION_MASTER_ERROR = "GET_AFFILIATION_MASTER_ERROR";
export const EXPORT_AFFILIATION_MASTER_ALLDATA_API = "/affiliation-master-export-all";
export const EXPORT_AFFILIATION_MASTER_API = "/affiliation-master-export";
export const IMPORT_AFFILIATION_MASTER_API = "/affiliation-master-import";
export const POST_AFFILIATION_MASTER_SUCCESS = "POST_AFFILIATION_MASTER_SUCCESS";
export const POST_AFFILIATION_MASTER_ERROR = "POST_AFFILIATION_MASTER_ERROR";
export const PUT_AFFILIATION_MASTER_SUCCESS = "PUT_AFFILIATION_MASTER_SUCCESS";
export const PUT_AFFILIATION_MASTER_ERROR = "PUT_AFFILIATION_MASTER_ERROR";

export const GET_SUBJECT_MASTER_API = "/subject-master";
export const GET_SUBJECT_MASTER_SUCCESS = "GET_SUBJECT_MASTER_SUCCESS";
export const GET_SUBJECT_MASTER_ERROR = "GET_SUBJECT_MASTER_ERROR";
export const EXPORT_SUBJECT_MASTER_ALLDATA_API = "/subject-master-export-all";
export const EXPORT_SUBJECT_MASTER_API = "/subject-master-export";
export const IMPORT_SUBJECT_MASTER_API = "/subject-master-import";
export const POST_SUBJECT_MASTER_SUCCESS = "POST_SUBJECT_MASTER_SUCCESS";
export const POST_SUBJECT_MASTER_ERROR = "POST_SUBJECT_MASTER_ERROR";
export const PUT_SUBJECT_MASTER_SUCCESS = "PUT_SUBJECT_MASTER_SUCCESS";
export const PUT_SUBJECT_MASTER_ERROR = "PUT_SUBJECT_MASTER_ERROR";
export const GET_SUBJECT_MASTER_LIST_API = "/subject-master-list";
export const GET_SUBJECT_MASTER_LIST_SUCCESS = 'GET_SUBJECT_MASTER_LIST_SUCCESS';
export const GET_SUBJECT_MASTER_LIST_ERROR = 'GET_SUBJECT_MASTER_LIST_ERROR';

export const GET_CAREER_COURSE_LEVEL_LIST_API = "/career-course-level-list";
export const GET_CAREER_COURSE_LEVEL_LIST_SUCCESS = "GET_CAREER_COURSE_LEVEL_LIST_SUCCESS";
export const GET_CAREER_COURSE_LEVEL_LIST_ERROR = "GET_CAREER_COURSE_LEVEL_LIST_ERROR";
export const GET_CAREER_COURSE_LEVEL_API = "/career-course-level";
export const GET_CAREER_COURSE_LEVEL_SUCCESS = "GET_CAREER_COURSE_LEVEL_SUCCESS";
export const GET_CAREER_COURSE_LEVEL_ERROR = "GET_CAREER_COURSE_LEVEL_ERROR";
export const EXPORT_CAREER_COURSE_LEVEL_ALLDATA_API = "/career-course-level-export-all";
export const EXPORT_CAREER_COURSE_LEVEL_API = "/career-course-level-export";
export const IMPORT_CAREER_COURSE_LEVEL_API = "/career-course-level-import";
export const POST_CAREER_COURSE_LEVEL_SUCCESS = "POST_CAREER_COURSE_LEVEL_SUCCESS";
export const POST_CAREER_COURSE_LEVEL_ERROR = "POST_CAREER_COURSE_LEVEL_ERROR";
export const PUT_CAREER_COURSE_LEVEL_SUCCESS = "PUT_CAREER_COURSE_LEVEL_SUCCESS";
export const PUT_CAREER_COURSE_LEVEL_ERROR = "PUT_CAREER_COURSE_LEVEL_ERROR";

export const GET_COURSE_TYPE_API = "/coursetype";
export const GET_COURSE_TYPE_SUCCESS = "GET_COURSE_TYPE_SUCCESS";
export const GET_COURSE_TYPE_ERROR = "GET_COURSE_TYPE_ERROR";
export const EXPORT_COURSE_TYPE_ALLDATA_API = "/coursetype-export-all";
export const EXPORT_COURSE_TYPE_API = "/coursetype-export";
export const IMPORT_COURSE_TYPE_API = "/coursetype-import";
export const POST_COURSE_TYPE_SUCCESS = "POST_COURSE_TYPE_SUCCESS";
export const POST_COURSE_TYPE_ERROR = "POST_COURSE_TYPE_ERROR";
export const PUT_COURSE_TYPE_SUCCESS = "PUT_COURSE_TYPE_SUCCESS";
export const PUT_COURSE_TYPE_ERROR = "PUT_COURSE_TYPE_ERROR";

export const GET_TASKS_STMT_MASTER_API = "/tasks-master";
export const GET_TASKS_STMT_MASTER_SUCCESS = "GET_TASKS_STMT_MASTER_SUCCESS";
export const GET_TASKS_STMT_MASTER_ERROR = "GET_TASKS_STMT_MASTER_ERROR";
export const EXPORT_TASKS_STMT_MASTER_ALLDATA_API = "/tasks-master-export-all";
export const EXPORT_TASKS_STMT_MASTER_API = "/tasks-master-export";
export const IMPORT_TASKS_STMT_MASTER_API = "/tasks-master-import";
export const POST_TASKS_STMT_MASTER_SUCCESS = "POST_TASKS_STMT_MASTER_SUCCESS";
export const POST_TASKS_STMT_MASTER_ERROR = "POST_TASKS_STMT_MASTER_ERROR";
export const PUT_TASKS_STMT_MASTER_SUCCESS = "PUT_TASKS_STMT_MASTER_SUCCESS";
export const PUT_TASKS_STMT_MASTER_ERROR = "PUT_TASKS_STMT_MASTER_ERROR";

export const GET_EMPLOYMENT_STATUS_LIST_API = "/employment-status-list";
export const GET_EMPLOYMENT_STATUS_LIST_SUCCESS = "GET_EMPLOYMENT_STATUS_LIST_SUCCESS";
export const GET_EMPLOYMENT_STATUS_LIST_ERROR = "GET_EMPLOYMENT_STATUS_LIST_ERROR";

export const GET_EMPLOYMENT_STATUS_MASTER_API = "/employment-status";
export const GET_EMPLOYMENT_STATUS_MASTER_SUCCESS = "GET_EMPLOYMENT_STATUS_MASTER_SUCCESS";
export const GET_EMPLOYMENT_STATUS_MASTER_ERROR = "GET_EMPLOYMENT_STATUS_MASTER_ERROR";
export const EXPORT_EMPLOYMENT_STATUS_MASTER_ALLDATA_API = "/employment-status-export-all";
export const EXPORT_EMPLOYMENT_STATUS_MASTER_API = "/employment-status-export";
export const IMPORT_EMPLOYMENT_STATUS_MASTER_API = "/employment-status-import";
export const POST_EMPLOYMENT_STATUS_MASTER_SUCCESS = "POST_EMPLOYMENT_STATUS_MASTER_SUCCESS";
export const POST_EMPLOYMENT_STATUS_MASTER_ERROR = "POST_EMPLOYMENT_STATUS_MASTER_ERROR";
export const PUT_EMPLOYMENT_STATUS_MASTER_SUCCESS = "PUT_EMPLOYMENT_STATUS_MASTER_SUCCESS";
export const PUT_EMPLOYMENT_STATUS_MASTER_ERROR = "PUT_EMPLOYMENT_STATUS_MASTER_ERROR";

export const GET_COURSE_ELIGIBILITY_MASTER_API = "/course-eligibility";
export const GET_COURSE_ELIGIBILITY_MASTER_SUCCESS = "GET_COURSE_ELIGIBILITY_MASTER_SUCCESS";
export const GET_COURSE_ELIGIBILITY_MASTER_ERROR = "GET_COURSE_ELIGIBILITY_MASTER_ERROR";
export const EXPORT_COURSE_ELIGIBILITY_MASTER_ALLDATA_API = "/course-eligibility-export-all";
export const EXPORT_COURSE_ELIGIBILITY_MASTER_API = "/course-eligibility-export";
export const IMPORT_COURSE_ELIGIBILITY_MASTER_API = "/course-eligibility-import";
export const POST_COURSE_ELIGIBILITY_MASTER_SUCCESS = "POST_COURSE_ELIGIBILITY_MASTER_SUCCESS";
export const POST_COURSE_ELIGIBILITY_MASTER_ERROR = "POST_COURSE_ELIGIBILITY_MASTER_ERROR";
export const PUT_COURSE_ELIGIBILITY_MASTER_SUCCESS = "PUT_COURSE_ELIGIBILITY_MASTER_SUCCESS";
export const PUT_COURSE_ELIGIBILITY_MASTER_ERROR = "PUT_COURSE_ELIGIBILITY_MASTER_ERROR";

export const GET_COURSE_EXAMINATION_API = "/course-examination";
export const GET_COURSE_EXAMINATION_SUCCESS = "GET_COURSE_EXAMINATION_SUCCESS";
export const GET_COURSE_EXAMINATION_ERROR = "GET_COURSE_EXAMINATION_ERROR";
export const EXPORT_COURSE_EXAMINATION_ALLDATA_API = "/course-examination-export-all";
export const EXPORT_COURSE_EXAMINATION_API = "/course-examination-export";
export const IMPORT_COURSE_EXAMINATION_API = "/course-examination-import";
export const POST_COURSE_EXAMINATION_SUCCESS = "POST_COURSE_EXAMINATION_SUCCESS";
export const POST_COURSE_EXAMINATION_ERROR = "POST_COURSE_EXAMINATION_ERROR";
export const PUT_COURSE_EXAMINATION_SUCCESS = "PUT_COURSE_EXAMINATION_SUCCESS";
export const PUT_COURSE_EXAMINATION_ERROR = "PUT_COURSE_EXAMINATION_ERROR";

export const GET_EXAMINATION_LIST_API = "/examination-list";
export const GET_EXAMINATION_LIST_SUCCESS = "GET_EXAMINATION_LIST_SUCCESS";
export const GET_EXAMINATION_LIST_ERROR = "GET_EXAMINATION_LIST_ERROR";

export const GET_STREAM_MASTER_LIST_API = "/stream-list";
export const GET_STREAM_MASTER_LIST_SUCCESS = "GET_STREAM_MASTER_LIST_SUCCESS";
export const GET_STREAM_MASTER_LIST_ERROR = "GET_STREAM_MASTER_LIST_ERROR";
export const GET_STREAM_MASTER_API = "/stream";
export const GET_STREAM_MASTER_SUCCESS = "GET_STREAM_MASTER_SUCCESS";
export const GET_STREAM_MASTER_ERROR = "GET_STREAM_MASTER_ERROR";
export const EXPORT_STREAM_MASTER_ALLDATA_API = "/stream-export-all";
export const EXPORT_STREAM_MASTER_API = "/stream-export";
export const IMPORT_STREAM_MASTER_API = "/stream-import";
export const POST_STREAM_MASTER_SUCCESS = "POST_STREAM_MASTER_SUCCESS";
export const POST_STREAM_MASTER_ERROR = "POST_STREAM_MASTER_ERROR";
export const PUT_STREAM_MASTER_SUCCESS = "PUT_STREAM_MASTER_SUCCESS";
export const PUT_STREAM_MASTER_ERROR = "PUT_STREAM_MASTER_ERROR";

export const GET_COLLEGE_EVENTDATES_API = "/college-eventdates";
export const GET_COLLEGE_EVENTDATES_SUCCESS = "GET_COLLEGE_EVENTDATES_SUCCESS";
export const GET_COLLEGE_EVENTDATES_ERROR = "GET_COLLEGE_EVENTDATES_ERROR";
export const EXPORT_COLLEGE_EVENTDATES_ALLDATA_API = "/college-eventdates-export-all";
export const EXPORT_COLLEGE_EVENTDATES_API = "/college-eventdates-export";
export const IMPORT_COLLEGE_EVENTDATES_API = "/college-eventdates-import";
export const POST_COLLEGE_EVENTDATES_SUCCESS = "POST_COLLEGE_EVENTDATES_SUCCESS";
export const POST_COLLEGE_EVENTDATES_ERROR = "POST_COLLEGE_EVENTDATES_ERROR";
export const PUT_COLLEGE_EVENTDATES_SUCCESS = "PUT_COLLEGE_EVENTDATES_SUCCESS";
export const PUT_COLLEGE_EVENTDATES_ERROR = "PUT_COLLEGE_EVENTDATES_ERROR";

export const GET_PUBLISH_DETAILS_LIST_API = "/publish-list";
export const GET_PUBLISH_DETAILS_LIST_SUCCESS = "GET_PUBLISH_DETAILS_LIST_SUCCESS";
export const GET_PUBLISH_DETAILS_LIST_ERROR = "GET_PUBLISH_DETAILS_LIST_ERROR";
export const GET_PUBLISH_DETAILS_API = "/publisher-details";
export const GET_PUBLISH_DETAILS_SUCCESS = "GET_PUBLISH_DETAILS_SUCCESS";
export const GET_PUBLISH_DETAILS_ERROR = "GET_PUBLISH_DETAILS_ERROR";
export const EXPORT_PUBLISH_DETAILS_ALLDATA_API = "/publisher-details-export-all";
export const EXPORT_PUBLISH_DETAILS_API = "/publisher-export";
export const IMPORT_PUBLISH_DETAILS_API = "/publisher-details-import";
export const POST_PUBLISH_DETAILS_SUCCESS = "POST_PUBLISH_DETAILS_SUCCESS";
export const POST_PUBLISH_DETAILS_ERROR = "POST_PUBLISH_DETAILS_ERROR";
export const PUT_PUBLISH_DETAILS_SUCCESS = "PUT_PUBLISH_DETAILS_SUCCESS";
export const PUT_PUBLISH_DETAILS_ERROR = "PUT_PUBLISH_DETAILS_ERROR";

export const GET_ITEM_MASTER_LIST_API = "/item-list";
export const GET_ITEM_MASTER_LIST_SUCCESS = "GET_ITEM_MASTER_LIST_SUCCESS";
export const GET_ITEM_MASTER_LIST_ERROR = "GET_ITEM_MASTER_LIST_ERROR";

export const GET_TOPIC_MASTER_LIST_API = "/topic-list";
export const GET_TOPIC_MASTER_LIST_SUCCESS = "GET_TOPIC_MASTER_LIST_SUCCESS";
export const GET_TOPIC_MASTER_LIST_ERROR = "GET_TOPIC_MASTER_LIST_ERROR";

export const GET_COURSE_TYPE_LIST_API = "/course-type-list";
export const GET_COURSE_TYPE_LIST_SUCCESS = "GET_COURSE_TYPE_LIST_SUCCESS";
export const GET_COURSE_TYPE_LIST_ERROR = "GET_COURSE_TYPE_LIST_ERROR";

export const GET_COURSE_LEVEL_LIST_API = "/course-level-list";
export const GET_COURSE_LEVEL_LIST_SUCCESS = "GET_COURSE_LEVEL_LIST_SUCCESS";
export const GET_COURSE_LEVEL_LIST_ERROR = "GET_COURSE_LEVEL_LIST_ERROR";

export const GET_AFFILITION_MASTER_API = "/affiliation";
export const GET_AFFILITION_MASTER_SUCCESS = "GET_AFFILITION_MASTER_SUCCESS";
export const GET_AFFILITION_MASTER_ERROR = "GET_AFFILITION_MASTER_ERROR";

export const GET_ENTITYTYPE_LIST_API = "/entitytype-list";
export const GET_ENTITYTYPE_LIST_SUCCESS = "GET_ENTITYTYPE_LIST_LIST_SUCCESS";
export const GET_ENTITYTYPE_LIST_ERROR = "GET_ENTITYTYPE_LIST_LIST_ERROR";

export const GET_MASTER_ENTITY_LIST_API = "/master-entity-list";
export const GET_MASTER_ENTITY_LIST_SUCCESS = "GET_MASTER_ENTITY_LIST_SUCCESS";
export const GET_MASTER_ENTITY_LIST_ERROR = "GET_MASTER_ENTITY_LIST_ERROR";

export const GET_MASTER_ENTITY_COLLEGE_LIST_API = "/college-list";
export const GET_MASTER_ENTITY_COLLEGE_LIST_SUCCESS = "GET_MASTER_ENTITY_COLLEGE_LIST_SUCCESS";
export const GET_MASTER_ENTITY_COLLEGE_LIST_ERROR = "GET_MASTER_ENTITY_COLLEGE_LIST_ERROR";

export const GET_ENTITYSUBTYPE_ENTITY_API = "/entitysubtype";
export const GET_ENTITYSUBTYPE_SUCCESS = "GET_ENTITYSUBTYPE_SUCCESS";
export const GET_ENTITYSUBTYPE_ERROR = "GET_ENTITYSUBTYPE_ERROR";

export const GET_RANK_API = "/rank";
export const DELETE_RANK_API = "/rank"
export const CREATE_RANK_API = "/rank"
export const EXPORT_RANK_API = "/rank-export";
export const EXPORT_ALL_RANK_API = "/rank-export-all";
export const IMPORT_RANK_API = "/rank-import";
export const GET_RANK_SUCCESS = "GET_RANK_SUCCESS";
export const GET_RANK_ERROR = "GET_RANK_ERROR";

export const GET_DISCIPLINE_API = "/discipline";
export const DELETE_DISCIPLINE_API = "/discipline";
export const CREATE_DISCIPLINE_API = "/discipline";
export const EXPORT_DISCIPLINE_API = "/discipline-export";
export const EXPORT_ALL_DISCIPLINE_API = "/discipline-export-all";
export const IMPORT_DISCIPLINE_API = "/discipline-import";
export const GET_DISCIPLINE_SUCCESS = "GET_DISCIPLINE_SUCCESS";
export const GET_DISCIPLINE_ERROR = "GET_DISCIPLINE_ERROR";

export const GET_ACADEMIC_API = "/academic";
export const DELETE_ACADEMIC_API = "/academic";
export const CREATE_ACADEMIC_API = "/academic";
export const EXPORT_ACADEMIC_API = "/academic-export";
export const EXPORT_ALL_ACADEMIC_API = "/academic-export-all";
export const IMPORT_ACADEMIC_API = "/academic-import";
export const GET_ACADEMIC_SUCCESS = "GET_DISCIPLINE_SUCCESS";
export const GET_ACADEMIC_ERROR = "GET_DISCIPLINE_ERROR";
export const GET_PROGRAMLEVEL_LIST_API = "/level-list";
export const GET_PROGRAMLEVEL_LIST_SUCCESS = "GET_PROGRAMLEVEL_LIST_SUCCESS";
export const GET_PROGRAMLEVEL_LIST_ERROR = "GET_PROGRAMLEVEL_LIST_ERROR";

export const GET_INTAKE_LIST_API = "/intake-list";
export const GET_INTAKE_LIST_SUCCESS = "GET_INTAKE_LIST_SUCCESS";
export const GET_INTAKE_LIST_ERROR = "GET_INTAKE_LIST_ERROR";

export const GET_PROGRAM_LIST_API = "/program-list";
export const GET_PROGRAM_LIST_SUCCESS = "GET_PROGRAM_LIST_SUCCESS";
export const GET_PROGRAM_LIST_ERROR = "GET_PROGRAM_LIST_ERROR";

export const GET_PROGRAM_API = "/program";
export const DELETE_PROGRAM_API = "/program";
export const CREATE_PROGRAM_API = "/program";
export const EXPORT_PROGRAM_API = "/program-export";
export const EXPORT_ALL_PROGRAM_API = "/program-export-all";
export const IMPORT_PROGRAM_API = "/program-import";
export const GET_PROGRAM_SUCCESS = "GET_PROGRAM_SUCCESS";
export const GET_PROGRAM_ERROR = "GET_PROGRAM_ERROR";

export const GET_DISCIPLINE_LIST_API = "/discipline-list"
export const GET_DISCIPLINE_LIST_SUCCESS = "GET_DISCIPLINE_LIST_SUCCESS";
export const GET_DISCIPLINE_LIST_ERROR = "GET_DISCIPLINE_LIST_ERROR";

export const GET_ACCREDITATION_API = "/accreditation-mapper";
export const DELETE_ACCREDITATION_API = "/accreditation-mapper";
export const CREATE_ACCREDITATION_API = "/accreditation-mapper";
export const EXPORT_ACCREDITATION_API = "/accreditation-export";
export const EXPORT_ALL_ACCREDITATION_API = "/accreditation-export-all";
export const IMPORT_ACCREDITATION_API = "/accreditation-import";
export const GET_ACCREDITATION_SUCCESS = "GET_ACCREDITATION_SUCCESS";
export const GET_ACCREDITATION_ERROR = "GET_ACCREDITATION_ERROR";

export const GET_ENTITYCAMPUS_API = "/campus";
export const DELETE_ENTITYCAMPUS_API = "/campus";
export const CREATE_ENTITYCAMPUS_API = "/campus";
export const EXPORT_ENTITYCAMPUS_API = "/campus-export";
export const EXPORT_ALL_ENTITYCAMPUS_API = "/campus-export-all";
export const IMPORT_ENTITYCAMPUS_API = "/campus-import";
export const GET_ENTITYCAMPUS_SUCCESS = "GET_ENTITYCAMPUS_SUCCESS";
export const GET_ENTITYCAMPUS_ERROR = "GET_ENTITYCAMPUS_ERROR";

export const GET_RANKINGMAPPER_API = "/ranking-mapper";
export const DELETE_RANKINGMAPPER_API = "/ranking-mapper";
export const CREATE_RANKINGMAPPER_API = "/ranking-mapper";
export const EXPORT_RANKINGMAPPER_API = "/ranking-mapper-export";
export const EXPORT_ALL_RANKINGMAPPER_API = "/ranking-mapper-export-all";
export const IMPORT_RANKINGMAPPER_API = "/ranking-mapper-import";
export const GET_RANKINGMAPPER_SUCCESS = "GET_RANKINGMAPPER_SUCCESS";
export const GET_RANKINGMAPPER_ERROR = "GET_RANKINGMAPPER_ERROR";

export const GET_RANKING_LIST_API = "/rank-list"
export const GET_RANKING_LIST_SUCCESS = "GET_RANKING_LIST_SUCCESS";
export const GET_RANKING_LIST_ERROR = "GET_RANKING_LIST_ERROR";

export const GET_COLLEGE_EVENT_API = "/college-event";
export const GET_COLLEGE_EVENT_LIST_API = "/college-event-list";
export const GET_COLLEGE_EVENT_LIST_SUCCESS = "GET_COLLEGE_EVENT_LIST_SUCCESS";
export const GET_COLLEGE_EVENT_LIST_ERROR = "GET_COLLEGE_EVENT_LIST_ERROR";
export const DELETE_COLLEGE_EVENT_API = "/college-event";
export const CREATE_COLLEGE_EVENT_API = "/college-event";
export const EXPORT_COLLEGE_EVENT_API = "/college-event-export";
export const EXPORT_ALL_COLLEGE_EVENT_API = "/college-event-export-all";
export const IMPORT_COLLEGE_EVENT_API = "/college-event-import";
export const GET_COLLEGE_EVENT_SUCCESS = "GET_COLLEGE_EVENT_SUCCESS";
export const GET_COLLEGE_EVENT_ERROR = "GET_COLLEGE_EVENT_ERROR";

export const GET_EXAMTYPE_API = "/examtype";
export const DELETE_EXAMTYPE_API = "/examtype";
export const CREATE_EXAMTYPE_API = "/examtype";
export const EXPORT_EXAMTYPE_API = "/examtype-export";
export const EXPORT_ALL_EXAMTYPE_API = "/examtype-export-all";
export const IMPORT_EXAMTYPE_API = "/examtype-import";
export const GET_EXAMTYPE_SUCCESS = "GET_EXAMTYPE_SUCCESS";
export const GET_EXAMTYPE_ERROR = "GET_EXAMTYPE_ERROR";
export const GET_EXAMTYPE_LIST_API = "/examtype-list";
export const GET_EXAMTYPE_LIST_SUCCESS = "GET_EXAMTYPE_LIST_SUCCESS";
export const GET_EXAMTYPE_LIST_ERROR = "GET_EXAMTYPE_LIST_ERROR";

export const GET_OCCUPATION_API = "/occupation";
export const GET_OCCUPATION_LIST_API = "/occupation-list";
export const DELETE_OCCUPATION_API = "/occupation";
export const CREATE_OCCUPATION_API = "/occupation";
export const EXPORT_OCCUPATION_API = "/occupation-export";
export const EXPORT_ALL_OCCUPATION_API = "/occupation-export-all";
export const IMPORT_OCCUPATION_API = "/occupation-import";
export const GET_OCCUPATION_SUCCESS = "GET_OCCUPATION_SUCCESS";
export const GET_OCCUPATION_ERROR = "GET_OCCUPATION_ERROR";
export const GET_OCCUPATION_LIST_SUCCESS = "GET_OCCUPATION_LIST_SUCCESS";
export const GET_OCCUPATION_LIST_ERROR = "GET_OCCUPATION_LIST_ERROR";

export const GET_OCCUPATIONCOURSE_API = "/occupation-course";
export const DELETE_OCCUPATIONCOURSE_API = "/occupation-course";
export const CREATE_OCCUPATIONCOURSE_API = "/occupation-course";
export const EXPORT_OCCUPATIONCOURSE_API = "/occupation-course-export";
export const EXPORT_ALL_OCCUPATIONCOURSE_API = "/occupation-course-export-all";
export const IMPORT_OCCUPATIONCOURSE_API = "/occupation-course-import";
export const GET_OCCUPATIONCOURSE_SUCCESS = "GET_OCCUPATIONCOURSE_SUCCESS";
export const GET_OCCUPATIONCOURSE_ERROR = "GET_OCCUPATIONCOURSE_ERROR";
export const POST_OCCUPATIONCOURSE_SUCCESS = "POST_OCCUPATIONCOURSE_SUCCESS";
export const POST_OCCUPATIONCOURSE_ERROR = "POST_OCCUPATIONCOURSE_ERROR";
export const PUT_OCCUPATIONCOURSE_SUCCESS = "PUT_OCCUPATIONCOURSE_SUCCESS";
export const PUT_OCCUPATIONCOURSE_ERROR = "PUT_OCCUPATIONCOURSE_ERROR";

export const GET_MASTERDEGREE_API = "/degree";
export const DELETE_MASTERDEGREE_API = "/degree";
export const CREATE_MASTERDEGREE_API = "/degree";
export const EXPORT_MASTERDEGREE_API = "/degree-export";
export const EXPORT_ALL_MASTERDEGREE_API = "/degree-export-all";
export const IMPORT_MASTERDEGREE_API = "/degree-import";
export const GET_MASTERDEGREE_SUCCESS = "GET_MASTERDEGREE_SUCCESS";
export const GET_MASTERDEGREE_ERROR = "GET_MASTERDEGREE_ERROR";

export const GET_ENTITYCOURSES_API = "/courses-entity";
export const DELETE_ENTITYCOURSES_API = "/courses-entity";
export const CREATE_ENTITYCOURSES_API = "/courses-entity";
export const EXPORT_ENTITYCOURSES_API = "/courses-entity-export";
export const EXPORT_ALL_ENTITYCOURSES_API = "/courses-entity-export-all";
export const IMPORT_ENTITYCOURSES_API = "/courses-entity-import";
export const GET_ENTITYCOURSES_SUCCESS = "GET_ENTITYCOURSES_SUCCESS";
export const GET_ENTITYCOURSES_ERROR = "GET_ENTITYCOURSES_ERROR";

export const GET_EVENTTYPE_LIST_API = "/event-type-list";
export const GET_EVENTTYPE_LIST_SUCCESS = "GET_EVENTTYPE_LIST_SUCCESS";
export const GET_EVENTTYPE_LIST_ERROR = "GET_EVENTTYPE_LIST_ERROR";
export const GET_COURSEMODE_LIST_API = "/coursemode-list"
export const GET_COURSEMODE_LIST_SUCCESS = "GET_COURSEMODE_LIST_SUCCESS";
export const GET_COURSEMODE_LIST_ERROR = "GET_COURSEMODE_LIST_ERROR";

export const GET_EVENTTYPE_API = "/event-type";
export const DELETE_EVENTTYPE_API = "/event-type";
export const CREATE_EVENTTYPE_API = "/event-type";
export const EXPORT_EVENTTYPE_API = "/event-type-export";
export const EXPORT_ALL_EVENTTYPE_API = "/event-type-export-all";
export const IMPORT_EVENTTYPE_API = "/event-type-import";
export const GET_EVENTTYPE_SUCCESS = "GET_EVENTTYPE_SUCCESS";
export const GET_EVENTTYPE_ERROR = "GET_EVENTTYPE_ERROR";

export const GET_CITY_API = "/city";
export const DELETE_CITY_API = "/city";
export const CREATE_CITY_API = "/city";
export const EXPORT_CITY_API = "/city-export";
export const EXPORT_ALL_CITY_API = "/city-export-all";
export const IMPORT_CITY_API = "/city-import";
export const GET_CITY_SUCCESS = "GET_CITY_SUCCESS";
export const GET_CITY_ERROR = "GET_CITY_ERROR";
export const GET_STATEID_LIST_API = "/state-list";
export const GET_STATEID_LIST_SUCCESS = "CITY_LIST_SUCCESS";
export const GET_STATEID_LIST_ERROR = "CITY_LIST_ERROR";

export const GET_RMOEMPLOYMENTSTATUS_API = "/occupation-employmentstatus";
export const DELETE_RMOEMPLOYMENTSTATUS_API = "/occupation-employmentstatus";
export const CREATE_RMOEMPLOYMENTSTATUS_API = "/occupation-employmentstatus";
export const EXPORT_RMOEMPLOYMENTSTATUS_API = "/occupation-employmentstatus-export";
export const EXPORT_ALL_RMOEMPLOYMENTSTATUS_API = "/occupation-employmentstatus-export-all";
export const IMPORT_RMOEMPLOYMENTSTATUS_API = "/occupation-employmentstatus-import";
export const GET_RMOEMPLOYMENTSTATUS_SUCCESS = "GET_RMOEMPLOYMENTSTATUS_SUCCESS";
export const GET_RMOEMPLOYMENTSTATUS_ERROR = "GET_RMOEMPLOYMENTSTATUS_ERROR";

export const GET_MASTER_STATE_API = "/state";
export const EXPORT_MASTER_STATE_API = "/state-export";
export const EXPORT_ALL_MASTER_STATE_API = "/state-export-all";
export const IMPORT_MASTER_STATE_API = "/state-import";
export const GET_MASTER_STATE_SUCCESS = "GET_MASTER_STATE_SUCCESS";
export const GET_MASTER_STATE_ERROR = "GET_MASTER_STATE_ERROR";
export const POST_MASTER_STATE_SUCCESS = "POST_MASTER_STATE_SUCCESS";
export const POST_MASTER_STATE_ERROR = "POST_MASTER_STATE_ERROR";
export const PUT_MASTER_STATE_SUCCESS = "PUT_MASTER_STATE_SUCCESS";
export const PUT_MASTER_STATE_ERROR = "PUT_MASTER_STATE_ERROR";
export const GET_MASTER_COUNTRY_LIST_API = "/country-list";
export const GET_MASTER_COUNTRY_LIST_SUCCESS = "MASTER_COUNTRY_LIST_SUCCESS";
export const GET_MASTER_COUNTRY_LIST_ERROR = "MASTER_COUNTRY_LIST_ERROR";

export const GET_OCCUPATIONEXAM_API = "/occupation-exam";
export const DELETE_OCCUPATIONEXAM_API = "/occupation-exam";
export const CREATE_OCCUPATIONEXAM_API = "/occupation-exam";
export const EXPORT_OCCUPATIONEXAM_API = "/occupation-exam-export";
export const EXPORT_ALL_OCCUPATIONEXAM_API = "/occupation-exam-export-all";
export const IMPORT_OCCUPATIONEXAM_API = "/occupation-exam-import";
export const GET_OCCUPATIONEXAM_SUCCESS = "GET_OCCUPATIONEXAM_SUCCESS";
export const GET_OCCUPATIONEXAM_ERROR = "GET_OCCUPATIONEXAM_ERROR";

export const GET_OCCUPATIONSALARY_API = "/salary";
export const DELETE_OCCUPATIONSALARY_API = "/salary";
export const CREATE_OCCUPATIONSALARY_API = "/salary";
export const EXPORT_OCCUPATIONSALARY_API = "/salary-export";
export const EXPORT_ALL_OCCUPATIONSALARY_API = "/salary-export-all";
export const IMPORT_OCCUPATIONSALARY_API = "/salary-import";
export const GET_OCCUPATIONSALARY_SUCCESS = "GET_OCCUPATIONSALARY_SUCCESS";
export const GET_OCCUPATIONSALARY_ERROR = "GET_OCCUPATIONSALARY_ERROR";

export const GET_OCCUPATIONEXPENSES_API = "/occupation-expenses";
export const DELETE_OCCUPATIONEXPENSES_API = "/occupation-expenses";
export const CREATE_OCCUPATIONEXPENSES_API = "/occupation-expenses";
export const EXPORT_OCCUPATIONEXPENSES_API = "/occupation-expenses-export";
export const EXPORT_ALL_OCCUPATIONEXPENSES_API = "/occupation-expenses-export-all";
export const IMPORT_OCCUPATIONEXPENSES_API = "/occupation-expenses-import";
export const GET_OCCUPATIONEXPENSES_SUCCESS = "GET_OCCUPATIONEXPENSES_SUCCESS";
export const GET_OCCUPATIONEXPENSES_ERROR = "GET_OCCUPATIONEXPENSES_ERROR";

export const GET_R_OCCUPATIONMETA_API = "/occupation-meta";
export const DELETE_R_OCCUPATIONMETA_API = "/occupation-meta";
export const CREATE_R_OCCUPATIONMETA_API = "/occupation-meta";
export const EXPORT_R_OCCUPATIONMETA_API = "/occupation-meta-export";
export const EXPORT_ALL_R_OCCUPATIONMETA_API = "/occupation-meta-export-all";
export const IMPORT_R_OCCUPATIONMETA_API = "/occupation-meta-import";
export const GET_R_OCCUPATIONMETA_SUCCESS = "GET_R_OCCUPATIONMETA_SUCCESS";
export const GET_R_OCCUPATIONMETA_ERROR = "GET_R_OCCUPATIONMETA_ERROR";
export const POST_R_OCCUPATIONMETA_SUCCESS = "POST_STUDY_ROUTE_PATH_SUCCESS";
export const POST_R_OCCUPATIONMETA_ERROR = "POST_STUDY_ROUTE_PATH_ERROR";
export const PUT_R_OCCUPATIONMETA_SUCCESS = "POST_STUDY_ROUTE_PATH_SUCCESS";
export const PUT_R_OCCUPATIONMETA_ERROR = "POST_STUDY_ROUTE_PATH_ERROR";

export const GET_ACCOMODATIONTYPE_API = "/accomodation-type";
export const DELETE_ACCOMODATIONTYPE_API = "/accomodation-type";
export const CREATE_ACCOMODATIONTYPE_API = "/accomodation-type";
export const EXPORT_ACCOMODATIONTYPE_API = "/accomodation-type-export";
export const EXPORT_ALL_ACCOMODATIONTYPE_API = "/accomodation-type-export-all";
export const IMPORT_ACCOMODATIONTYPE_API = "/accomodation-type-import";
export const GET_ACCOMODATIONTYPE_SUCCESS = "GET_ACCOMODATIONTYPE_SUCCESS";
export const GET_ACCOMODATIONTYPE_ERROR = "GET_ACCOMODATIONTYPE_ERROR";

export const GET_RMOBENCHMARKHOUR_API = "/occupation-benchmark";
export const DELETE_RMOBENCHMARKHOUR_API = "/occupation-benchmark";
export const CREATE_RMOBENCHMARKHOUR_API = "/occupation-benchmark";
export const EXPORT_RMOBENCHMARKHOUR_API = "/occupation-benchmark-export";
export const EXPORT_ALL_RMOBENCHMARKHOUR_API = "/occupation-benchmark-export-all";
export const IMPORT_RMOBENCHMARKHOUR_API = "/occupation-benchmark-import";
export const GET_RMOBENCHMARKHOUR_SUCCESS = "GET_RMOBENCHMARKHOUR_SUCCESS";
export const GET_RMOBENCHMARKHOUR_ERROR = "GET_RMOBENCHMARKHOUR_ERROR";

export const GET_RMOQUALIFICATION_LIST_API = "/occupation-qualification-list";
export const GET_RMOQUALIFICATION_LIST_SUCCESS = "GET_RMOQUALIFICATION_LIST_SUCCESS";
export const GET_RMOQUALIFICATION_LIST_ERROR = "GET_RMOQUALIFICATION_LIST_ERROR";
export const GET_RMOQUALIFICATION_API = "/occupation-qualification";
export const DELETE_RMOQUALIFICATION_API = "/occupation-qualification";
export const CREATE_RMOQUALIFICATION_API = "/occupation-qualification";
export const EXPORT_RMOQUALIFICATION_API = "/occupation-qualification-export";
export const EXPORT_ALL_RMOQUALIFICATION_API = "/occupation-qualification-export-all";
export const IMPORT_RMOQUALIFICATION_API = "/occupation-qualification-import";
export const GET_RMOQUALIFICATION_SUCCESS = "GET_RMOQUALIFICATION_SUCCESS";
export const GET_RMOQUALIFICATION_ERROR = "GET_RMOQUALIFICATION_ERROR";

export const GET_RMOPREGCARCODE_LIST_API = "/occupation-master-list";
export const GET_RMOPREGCARCODE_LIST_SUCCESS = "GET_RMOPREGCARCODE_LIST_SUCCESS";
export const GET_RMOPREGCARCODE_LIST_ERROR = "GET_RMOPREGCARCODE_LIST_ERROR";
export const GET_RMOPROGRESSION_API = "/occupation-progression";
export const DELETE_RMOPROGRESSION_API = "/occupation-progression";
export const CREATE_RMOPROGRESSION_API = "/occupation-progression";
export const EXPORT_RMOPROGRESSION_API = "/occupation-progression-export";
export const EXPORT_ALL_RMOPROGRESSION_API = "/occupation-progression-export-all";
export const IMPORT_RMOPROGRESSION_API = "/occupation-progression-import";
export const GET_RMOPROGRESSION_SUCCESS = "GET_RMOPROGRESSION_SUCCESS";
export const GET_RMOPROGRESSION_ERROR = "GET_RMOPROGRESSION_ERROR";

export const GET_COUNSELLOR_API_DATA = "/counselor";
export const GET_COUNSELLOR_API_DATA_SUCCESS = "GET_COUNSELLOR_API_DATA_SUCCESS";
export const GET_COUNSELLOR_API_DATA_ERROR = "GET_COUNSELLOR_API_DATA_ERROR";

export const ADMIN_UPDATE_ICSC_STATUS = "/counselor/admin-update-icsc-status";
export const ADMIN_UPDATE_ICSC_STATUS_SUCCESS = "ADMIN_UPDATE_ICSC_STATUS_SUCCESS";
export const ADMIN_UPDATE_ICSC_STATUS_ERROR = "ADMIN_UPDATE_ICSC_STATUS_ERROR";

export const GET_ENTITIES_URL = "/entities"
export const GET_ENTITY_LIST = "GET_ENTITY_LIST"
export const GET_ENTITY_DETAILS = "GET_ENTITY_DETAILS"
export const SET_ENTITY_STATUS = "SET_ENTITY_STATUS"
export const GET_ENTITY_FILTER_LIST = "GET_ENTITY_FILTER_LIST"

export const GET_EXTERNAL_USERS_URL = "/external-users"
export const GET_EXTERNAL_USER_LIST = "GET_EXTERNAL_USER_LIST"
export const GET_EXTERNAL_USER_DETAILS = "GET_EXTERNAL_USER_DETAILS"
export const CREATE_EXTERNAL_USER = "CREATE_EXTERNAL_USER"
export const UPDATE_EXTERNAL_USER = "UPDATE_EXTERNAL_USER"

export const GET_INTERNAL_USERS_URL = "/internal-users"
export const GET_INTERNAL_USERS_LIST = "GET_INTERNAL_USERS_LIST"
export const GET_INTERNAL_USERS_DETAILS = "GET_INTERNAL_USERS_DETAILS"
export const CREATE_INTERNAL_USER = "CREATE_INTERNAL_USER"
export const UPDATE_INTERNAL_USER = "UPDATE_INTERNAL_USER"

export const ENABLE_INTERNAL_USER = "ENABLE_INTERNAL_USER"
export const DISABLE_INTERNAL_USER = "DISABLE_INTERNAL_USER"
export const GLOBAL_SIGNOUT_INTERNAL_USER = "GLOBAL_SIGNOUT_INTERNAL_USER"
export const INTERNAL_RESET_PASSWORD = "INTERNAL_RESET_PASSWORD"
export const INTERNAL_USER_AUTH_EVENTS = "INTERNAL_USER_AUTH_EVENTS"

export const ENABLE_EXTERNAL_USER = "ENABLE_EXTERNAL_USER"
export const DISABLE_EXTERNAL_USER = "DISABLE_EXTERNAL_USER"
export const GLOBAL_SIGNOUT_EXTERNAL_USER = "GLOBAL_SIGNOUT_EXTERNAL_USER"
export const EXTERNAL_RESET_PASSWORD = "EXTERNAL_RESET_PASSWORD"
export const EXTERNAL_USER_AUTH_EVENTS = "EXTERNAL_USER_AUTH_EVENTS"

export const GET_EXTERNAL_USER_ENTITIES = "GET_EXTERNAL_USER_ENTITIES"
export const EXTERNAL_UNLINK_ENTITY = "EXTERNAL_UNLINK_ENTITY"
export const EXTERNAL_ADD_LINKED_ACCOUNTS = "EXTERNAL_ADD_LINKED_ACCOUNTS"

export const GET_COUNSELLOR_STATUS_DATA_URL = "/counselor/all-counselors-status-data"
export const GET_COUNSELLOR_STATUS_DATA_SUCCESS = "GET_COUNSELLOR_STATUS_DATA_SUCCESS"
export const GET_COUNSELLOR_STATUS_DATA_ERROR = "GET_COUNSELLOR_STATUS_DATA_ERROR"
export const GET_COUNSELLOR_LIST_URL = "/counselor/all-counselors-listing"
export const GET_COUNSELLOR_LIST = "GET_COUNSELLOR_LIST"
export const GET_COUNSELLOR_LIST_ALL = "GET_COUNSELLOR_LIST_ALL"

export const GET_SELECTED_COUNSELLOR_LIST_URL = "/counselor/listing"
export const GET_SELECTED_COUNSELLOR_LIST = "GET_SELECTED_COUNSELLOR_LIST"

export const GET_COUNSELLOR_DETAILS_URL = "/counselor"
export const GET_COUNSELLOR_DETAILS_SUCCESS = "GET_COUNSELLOR_DETAILS_SUCCESS"
export const GET_COUNSELLOR_DETAILS_ERROR = "GET_COUNSELLOR_DETAILS_ERROR"

export const GET_COUNSELLOR_AVAILABILITY_URL = "/counselor/availability"
export const GET_COUNSELLOR_AVAILABILITY_SUCCESS = "GET_COUNSELLOR_AVAILABILITY_SUCCESS"
export const GET_COUNSELLOR_AVAILABILITY_ERROR = "GET_COUNSELLOR_AVAILABILITY_ERROR"

export const GET_COUNSELLOR_EXCEPTION_URL = "/counselor/availability/exception"
export const GET_COUNSELLOR_EXCEPTION_SUCCESS = "GET_COUNSELLOR_EXCEPTION_SUCCESS"
export const GET_COUNSELLOR_EXCEPTION_ERROR = "GET_COUNSELLOR_EXCEPTION_ERROR"

export const GET_META_URL = "/meta"
export const GET_META_SUCCESS = "GET_META_SUCCESS"
export const GET_META_ERROR = "GET_META_ERROR"

export const SAVE_META_URL = "/meta"
export const SAVE_META_SUCCESS = "SAVE_META_SUCCESS"
export const SAVE_META_ERROR = "SAVE_META_ERROR"

export const GET_COUNSELLOR_OVERVIEW_URL = "/counselor"
export const GET_COUNSELLOR_OVERVIEW_SUCCESS = "GET_COUNSELLOR_OVERVIEW_SUCCESS"
export const GET_COUNSELLOR_OVERVIEW_ERROR = "GET_COUNSELLOR_OVERVIEW_ERROR"
export const GET_LEARNERS_LIST_URL = "/counselor/learners"
export const GET_LEARNERS_LIST = "GET_LEARNERS_LIST"
export const GET_SESSION_LIST_URL = "/counselor/session"
export const GET_SESSION_LIST = "GET_SESSION_LIST"
export const GET_RUNNING_SESSIONS_URL = "/counselor/running-sessions"
export const GET_RUNNING_SESSIONS = "GET_RUNNING_SESSIONS"
export const GET_LEARNER_SESSION_LIST = "GET_LEARNER_SESSION_LIST"

export const GET_SESSION_LOGS_URL = "/user/sessionlog"
export const GET_SESSION_LOGS = "GET_SESSION_LOGS"

export const GET_COUNSELLOR_STATS_URL = "/counselor/listing/typevisecount"
export const GET_COUNSELLOR_STATS = "GET_COUNSELLOR_STATS"

export const GET_SELECTED_COUNSELLOR_STATS_URL = "/counselor/listing/count";
export const GET_SELECTED_COUNSELLOR_STATS = "GET_SELECTED_COUNSELLOR_STATS"

export const CANCEL_SESSION_URL = "/user/session"
export const CANCEL_SESSION_SUCCESS = "CANCEL_SESSION_SUCCESS"
export const CANCEL_SESSION_ERROR = "CANCEL_SESSIOM_ERROR"

export const CHANGE_COUNSELLOR_URL = "/counselor/change"
export const CHANGE_COUNSELLOR_SUCCESS = "CHANGE_COUNSELLOR_SUCCESS"
export const CHANGE_COUNSELLOR_ERROR = "CHANGE_COUNSELLOR_ERROR"

export const GET_FEEDBACK_LIST_URL = "/counselor/feedback"
export const GET_FEEDBACK_LIST = "GET_FEEDBACK_LIST"
export const GET_FEEDBACK_DETAILS = "GET_FEEDBACK_DETAILS"

export const GET_DASHBOARD_LEARNER_LIST_URL = "/counselor/all-learners-list"
export const GET_DASHBOARD_LEARNER_SESSION_LIST_URL = "/counselor/learner-session"
export const GET_DASHBOARD_LEARNER_LIST = "GET_DASHBOARD_LEARNER_LIST"
export const GET_DASHBOARD_LEARNER_DETAILS = "GET_DASHBOARD_LEARNER_DETAILS"

export const GET_DASHBOARD_STATUS_DATA_URL = "/counselor/dashboardstats"
export const GET_DASHBOARD_STATUS_DATA_SUCCESS = "GET_DASHBOARD_STATUS_DATA_SUCCESS"
export const GET_DASHBOARD_STATUS_DATA_ERROR = "GET_DASHBOARD_STATUS_DATA_ERROR"
export const GET_ACTION_PLAN_URL = "/counselor/action-plan"
export const GET_ACTION_PLAN_SUCCESS = "GET_ACTION_PLAN_SUCCESS"
export const GET_ACTION_PLAN_ERROR = "GET_ACTION_PLAN_ERROR"

export const PUT_VOID_BILL = "/counselor/voidbill"
export const GET_CHANGE_COUNSELLOR_URL = "/counselor/available-counselors";
export const GET_CHANGE_COUNSELLOR_SUCCESS = "GET_CHANGE_COUNSELLOR_SUCCESS";
export const GET_CHANGE_COUNSELLOR_ERROR = "GET_CHANGE_COUNSELLOR_ERROR";

export const UPDATE_SESSION_COUNSELLOR_URL = "/user/assign-counselor";
export const GET_COUNSELLOR_OCCUPANCY_URL = "/counselor/occupancy"
export const GET_COUNSELLOR_OCCUPANCY_LIST = "GET_COUNSELLOR_OCCUPANCY_LIST"

export const GET_PAYROLL_URL = "/counselor/payroll"
export const GET_PAYROLL_SUCCESS = "GET_PAYROLL_SUCCESS"
export const GET_PAYROLL_ERROR = "GET_PAYROLL_ERROR"

export const GET_FEEDBACKLIST_URL = "/user/feedbacklisting";
export const GET_FEEDBACKLIST_SUCCESS = "GET_FEEDBACKLIST_SUCCESS";
export const GET_FEEDBACKLIST_ERROR = "GET_FEEDBACKLIST_ERROR";

export const UPDATE_PLAN_NAME = "/counselor/plantype";
export const POST_UPGRADE_PAYROLL = "/counselor/payroll"
export const GET_REASON_LIST = "/counselor/reason-list"
export const GET_REASON_SUCCESS = "GET_REASON_SUCCESS"
export const GET_REASON_ERROR = "GET_REASON_ERROR"

export const PUT_COUNSELLOR_STATUS = "/counselor/onboarded-status"

export const GET_TEST_RESULT = "/counselor/user-test-report"
export const TEST_RESULT_SUCCESS = "TEST_RESULT_SUCCESS"
export const TEST_RESULT_ERROR = "TEST_RESULT_ERROR"

export const GET_INTERVIEWER_LIST_URL = "/counselor/interviewer-active";
export const GET_INTERVIEWER_LIST_SUCCESS = "GET_INTERVIEWER_LIST_SUCCESS";
export const GET_INTERVIEWER_LIST_ERROR = "GET_INTERVIEWER_LIST_ERROR";

export const POST_MOCK_INTERVIEW_URL = "/counselor/interview";
export const POST_MOCK_INTERVIEW_SUCCESS = "POST_MOCK_INTERVIEW_SUCCESS";
export const POST_MOCK_INTERVIEW_ERROR = "POST_MOCK_INTERVIEW_SUCCESS";

export const GET_INTERVIEWER_LIST = "/counselor/interviewer"
export const GET_INTERVIEWER_SUCCESS = "GET_INTERVIEWER_SUCCESS"
export const GET_INTERVIEWER_ERROR = "GET_INTERVIEWER_ERROR"
export const POST_INTERVIEWER_DETAILS = "/counselor/interviewer"

export const POST_INTERVIEW_FEEDBACK = "/counselor/interview-feedback"
export const GET_DOCUMENT_LIST_URL = "/counselor/document/";
export const GET_DOCUMENT_LIST_SUCCESS = "GET_DOCUMENT_LIST_SUCCESS";
export const GET_DOCUMENT_LIST_ERROR = "GET_DOCUMENT_LIST_ERROR";

export const CHANGE_DOCUMENT_STATUS_URL = "/counselor/document/";
export const CHANGE_DOCUMENT_STATUS_SUCCESS = "CHANGE_DOCUMENT_STATUS_SUCCESS";
export const CHANGE_DOCUMENT_STATUS_ERROR = "CHANGE_DOCUMENT_STATUS_ERROR";

export const GET_INTERVIEW_TITLE = "/counselor/interview-title";
export const INTERVIEW_TITLE_SUCCESS = "INTERVIEW_TITLE_SUCCESS";
export const INTERVIEW_TITLE_ERROR = "INTERVIEW_TITLE_ERROR";

export const GET_PLANS_URL = "/counselor/profile-type";
export const GET_PLANS_SUCCESS = "GET_PLANS_SUCCESS";
export const GET_PLANS_ERROR = "GET_PLANS_ERROR"

export const GET_SCORE_TRACE_URL = "/counselor/scoretrace";
export const GET_SCORE_TRACE_SUCCESS = "GET_SCORE_TRACE_SUCCESS";
export const GET_SCORE_TRACE_ERROR = "GET_SCORE_TRACE_ERROR"

export const POST_MOCK_SESSION_URL = "/counselor/mocksession";
export const POST_MOCK_SESSION_SUCCESS = "POST_MOCK_SESSION_SUCCESS";
export const POST_MOCK_SESSION_ERROR = "POST_MOCK_SESSION_ERROR";

export const GET_ENTITIES_ACTIVE_PLAN = "/entities/active-plan";
export const ENTITIES_ACTIVE_PLAN_SUCCESS = "ENTITIES_ACTIVE_PLAN_SUCCESS";
export const ENTITIES_ACTIVE_PLAN_ERROR = "ENTITIES_ACTIVE_PLAN_ERROR";

export const GET_ACTIVE_ENTITIES = "/entities/active-entity";
export const GET_ACTIVE_ENTITIES_SUCCESS = "GET_ACTIVE_ENTITIES_SUCCESS";
export const GET_ACTIVE_ENTITIES_ERROR = "GET_ACTIVE_ENTITIES_ERROR";

export const POST_COUNSELLOR_PRICE = "/counselor/commercial";
export const POST_ENTITIES_ASSIGN_PACKAGE = "/entities/assign-package";
export const ENTITIES_ASSIGN_PACKAGE_SUCCESS = "ENTITIES_ASSIGN_PACKAGE_SUCCESS";
export const ENTITIES_ASSIGN_PACKAGE_ERROR = "ENTITIES_ASSIGN_PACKAGE_ERROR";

export const GET_ENTITIES_ASSIGNED_PACKAGE = "/entities/assigned-package";
export const ENTITIES_ASSIGNED_PACKAGE_SUCCESS = "ENTITIES_ASSIGNED_PACKAGE_SUCCESS";
export const ENTITIES_ASSIGNED_PACKAGE_ERROR = "ENTITIES_ASSIGNED_PACKAGE_ERROR";

export const GET_SESSION_LISTING = "/counselor/session-completed";
export const GET_SESSION_LISTING_SUCCESS = "GET_SESSION_LISTING_SUCCESS";
export const GET_SESSION_LISTING_ERROR = "GET_SESSION_LISTING_ERROR";
export const GET_ENTITY_USER_DETAILS = "/entities/entity-userdetails";
export const GET_ENTITY_USER_DETAILS_SUCCESS = "GET_ENTITY_USER_DETAILS_SUCCESS";
export const GET_ENTITY_USER_DETAILS_ERROR = "GET_ENTITY_USER_DETAILS_ERROR";

export const POST_ENTITY_USER_DETAILS = "/entities/checkout-subscription";
export const POST_ENTITY_USER_DETAILS_SUCCESS = "POST_ENTITY_USER_DETAILS_SUCCESS";
export const POST_ENTITY_USER_DETAILS_ERROR = "POST_ENTITY_USER_DETAILS_ERROR";

export const GET_ENTITY_ITEM_DETAILS = "/entities/entity-items";
export const GET_ENTITY_ITEM_DETAILS_SUCCESS = "GET_ENTITY_ITEM_DETAILS_SUCCESS";
export const GET_ENTITY_ITEM_DETAILS_ERROR = "GET_ENTITY_ITEM_DETAILS_ERROR";

export const GET_GLOBAL_TAX_LIST = "/global/taxlist";
export const GET_GLOBAL_TAX_LIST_SUCCESS = "GET_GLOBAL_TAX_LIST_SUCCESS";
export const GET_GLOBAL_TAX_LIST_ERROR = 'GET_GLOBAL_TAX_LIST_ERROR';

export const GET_ENTITIES_MASTER_PLAN = "/entities/master-plan";
export const GET_ENTITIES_MASTER_PLAN_SUCCESS = "GET_ENTITIES_MASTER_PLAN_SUCCESS";
export const GET_ENTITIES_MASTER_PLAN_ERROR = "GET_ENTITIES_MASTER_PLAN_ERROR";

export const GET_ENTITIES_ITEM_MASTER = "/entities/item-master";
export const GET_ENTITIES_ITEM_MASTER_SUCCESS = "GET_ENTITIES_ITEM_MASTER_SUCCESS";
export const GET_ENTITIES_ITEM_MASTER_ERROR = "GET_ENTITIES_ITEM_MASTER_ERROR";

export const POST_GLOBAL_ITEMS = "/global/items";
export const POST_GLOBAL_ITEMS_SUCCESS = "POST_GLOBAL_ITEMS_SUCCESS";
export const POST_GLOBAL_ITEMS_ERROR = "POST_GLOBAL_ITEMS_ERROR";

export const GET_ALL_ENTITIES = "/entities/allEntities";
export const GET_ALL_ENTITIES_SUCCESS = "GET_ALL_ENTITIES_SUCCESS";
export const GET_ALL_ENTITIES_ERROR = "GET_ALL_ENTITIES_ERROR";

export const POST_ENTITIES_MAP_ITEM = "/entities/map-item";
export const POST_ENTITIES_MAP_ITEM_SUCCESS = "POST_ENTITIES_MAP_ITEM_SUCCESS";
export const POST_ENTITIES_MAP_ITEM_ERROR = "POST_ENTITIES_MAP_ITEM_ERROR";

export const CHANGE_ENTITY_PACKAGE = "/entities/entity-package";
export const CHANGE_ENTITY_PACKAGE_SUCCESS = "CHANGE_ENTITY_PACKAGE_SUCCESS";
export const CHANGE_ENTITY_PACKAGE_ERROR = "CHANGE_ENTITY_PACKAGE_ERROR";

export const GET_COMMERCIAL_PRICING = "/counselor/commercial";
export const GET_COMMERCIAL_SUCCESS = "GET_COMMERCIAL_SUCCESS";
export const GET_COMMERCIAL_ERROR = "GET_COMMERCIAL_ERROR";

export const GET_SESSION_SLOTS_OVERRIDE_LISTING = "/global/override";
export const GET_SESSION_SLOTS_OVERRIDE_LISTING_SUCCESS = "GET_SESSION_SLOTS_OVERRIDE_LISTING_SUCCESS";
export const GET_SESSION_SLOTS_OVERRIDE_LISTING_ERROR = "GET_SESSION_SLOTS_OVERRIDE_LISTING_ERROR";

export const GET_VIEW_FEEDBACK = "/counselor/interview-feedback";
export const GET_VIEW_FEEDBACK_SUCCESS = "GET_VIEW_FEEDBACK_SUCCESS";
export const GET_VIEW_FEEDBACK_ERROR = "GET_VIEW_FEEDBACK_ERROR";

export const GET_PREMIUM_COUNT = "/user/premium-users";
export const GET_PREMIUM_COUNT_SUCCESS = "GET_PREMIUM_COUNT_SUCCESS";
export const GET_PREMIUM_COUNT_ERROR = "GET_PREMIUM_COUNT_ERROR";

export const GET_ACTIVE_USERS = "/user/active-users";
export const GET_ACTIVE_USERS_SUCCESS = "GET_ACTIVE_USERS_SUCCESS";
export const GET_ACTIVE_USERS_ERROR = "GET_ACTIVE_USERS_ERROR";

export const GET_ONBOARDING_STATUS = "/counselor/onboarding-status-count";
export const GET_ONBOARDING_STATUS_SUCCESS = "GET_ONBOARDING_STATUS_SUCCESS";
export const GET_ONBOARDING_STATUS_ERROR = "GET_ONBOARDING_STATUS_ERROR";

export const GET_SCHEDULED_SESSION_LISTING = "/counselor/session-scheduled";
export const GET_SCHEDULED_SESSION_LISTING_SUCCESS = "GET_SCHEDULED_SESSION_LISTING_SUCCESS";
export const GET_SCHEDULED_SESSION_LISTING_ERROR = "GET_SCHEDULED_SESSION_LISTING_ERROR";

export const GET_INACTIVE_USERS = "/user/inactive-users";
export const GET_INACTIVE_USERS_SUCCESS = "GET_INACTIVE_USERS_SUCCESS";
export const GET_INACTIVE_USERS_ERROR = "GET_INACTIVE_USERS_ERROR";

export const DELETE_SESSION_OVERRIDE = "/global/override";
export const DELETE_SESSION_OVERRIDE_SUCCESS = "DELETE_SESSION_OVERRIDE_SUCCESS";
export const DELETE_SESSION_OVERRIDE_ERROR = "DELETE_SESSION_OVERRIDE_ERROR";

export const GET_COUNSELLOR_COUNTS = "/counselor/counts-active-scheduled";
export const GET_COUNSELLOR_COUNTS_SUCCESS = "GET_COUNSELLOR_COUNTS_SUCCESS";
export const GET_COUNSELLOR_COUNTS_ERROR = "GET_COUNSELLOR_COUNTS_ERROR";

export const GET_PAST_COUNSELLOR_COUNTS = "/counselor/counts-inactive-completed";
export const GET_PAST_COUNSELLOR_COUNTS_SUCCESS = "GET_PAST_COUNSELLOR_COUNTS_SUCCESS";
export const GET_PAST_COUNSELLOR_COUNTS_ERROR = "GET_PAST_COUNSELLOR_COUNTS_ERROR";

export const GET_GLOBAL_AVAILABILITY = "/global/availibility";
export const GET_GLOBAL_AVAILABILITY_SUCCESS = "GET_GLOBAL_AVAILABILITY_SUCCESS";
export const GET_GLOBAL_AVAILABILITY_ERROR = "GET_GLOBAL_AVAILABILITY_ERROR";

export const GET_SESSIONS_LIST = "/user/sessionlist";
export const GET_SESSIONS_SUCCESS = "GET_SESSIONS_SUCCESS";
export const GET_SESSIONS_ERROR = "GET_SESSIONS_ERROR";
export const GET_COUNSELLOR_PAYROLL_GRP = "/counselor/payroll-groups";
export const GET_COUNSELLOR_PAYROLL_GRP_SUCCESS = "GET_COUNSELLOR_PAYROLL_GRP_SUCCESS";
export const GET_COUNSELLOR_PAYROLL_GRP_ERROR = "GET_COUNSELLOR_PAYROLL_GRP_ERROR";

export const GET_COUNSELLOR_RATING = "/counselor/rating";
export const GET_COUNSELLOR_RATING_SUCCESS = "GET_COUNSELLOR_RATING_SUCCESS";
export const GET_COUNSELLOR_RATING_ERROR = "GET_COUNSELLOR_RATING_ERROR";

export const GET_COUNSELLOR_SESSION_GRP = "/counselor/session-groups";
export const GET_COUNSELLOR_SESSION_GRP_SUCCESS = "GET_COUNSELLOR_SESSION_GRP_SUCCESS";
export const GET_COUNSELLOR_SESSION_GRP_ERROR = "GET_COUNSELLOR_SESSION_GRP_ERROR";

export const GET_ENTITY_PACKAGE = "/entities/entity-package";
export const GET_ENTITY_PACKAGE_SUCCESS = "GET_ENTITY_PACKAGE_SUCCESS";
export const GET_ENTTIY_PACKAGE_ERROR = "GET_ENTTIY_PACKAGE_ERROR";

export const POST_ENTITY_PACKAGE = "/entities/entity-package";
export const POST_ENTITY_PACKAGE_SUCCESS = "POST_ENTITY_PACKAGE_SUCCESS";
export const POST_ENTITY_PACKAGE_ERROR = "POST_ENTITY_PACKAGE_ERROR";

export const GET_SESSIONS_DETAIL = "/counselor/session-user-detail";
export const GET_SESSIONS_DETAIL_SUCCESS = "GET_SESSIONS_DETAIL_SUCCESS";
export const GET_SESSIONS_DETAIL_ERROR = "GET_SESSIONS_DETAIL_ERROR";

export const GET_ACTIVE_LANGUAGES = "/counselor/active-languages";
export const GET_LANGUAGES_SUCCESS = "GET_LANGUAGES_SUCCESS";
export const GET_LANGUAGES_ERROR = "GET_LANGUAGES_ERROR";

export const GET_ENTITIES_MAPPED_ITEMS = "/entities/mapped-items";
export const GET_ENTITIES_MAPPED_ITEMS_SUCCESS = "GET_ENTITIES_MAPPED_ITEMS_SUCCESS";
export const GET_ENTITIES_MAPPED_ITEMS_ERROR = "GET_ENTITIES_MAPPED_ITEMS_ERROR";

export const PATCH_UPDATE_EMAIL = "/counselor/update-email";

export const GET_LEARNING_HUB_ORDER = "/learning/list";
export const GET_LEARNING_HUB_ORDER_SUCCESS = "GET_LEARNING_HUB_ORDER_SUCCESS";
export const GET_LEARNING_HUB_ORDER_ERROR = "GET_LEARNING_HUB_ORDER_ERROR";

export const GET_OLD_ACTIONPLANS = "/counselor/learner-all-actionplan";
export const GET_OLD_ACTIONPLAN_SUCCESS = "GET_OLD_ACTIONPLAN_SUCCESS";
export const GET_OLD_ACTIONPLAN_ERROR = "GET_OLD_ACTIONPLAN_ERROR";

export const GET_LEARNING_HUB_ORDER_DETAIL = "/learning/item"
export const GET_LEARNING_HUB_ORDER_DETAIL_SUCCESS = "GET_LEARNING_HUB_ORDER_DETAIL_SUCCESS";
export const GET_LEARNING_HUB_ORDER_DETAIL_ERROR = "GET_LEARNING_HUB_ORDER_DETAIL_ERROR";

export const CREATE_AWB_URL = "/shiprocket/courier/generate-awb-for-shipment";
export const GENERATE_PICKUP_URL = "/shiprocket/courier/request-for-shipment-pickup/";
export const TRACK_ORDER_URL = "/shiprocket/tracking/";
export const GENERATE_MANIFEST_URL = "/shiprocket/manifest/generate";
export const GENERATE_LABEL_URL = "/shiprocket/label/generate";
export const GENERATE_INVOICE_URL = "/shiprocket/invoice/generate"
export const CANCEL_SHIPMENT_URL = "/shiprocket/shipment/cancel"
export const GET_ORDER_STATUS = "/shiprocket/order/"
export const PRINT_MANIFEST = "/shiprocket/manifest/print"
export const GET_COURIER_PARTNERS = "/shiprocket/courier/serviceability"
export const CANCEL_ORDER_URL = "/shiprocket/order/cancel"

export const GET_ALLOWED_ROUTES = "/webadmin/routes";
export const GET_ALLOWED_ROUTES_SUCCESS = "GET_ALLOWED_ROUTES_SUCCESS";
export const GET_ALLOWED_ROUTES_ERROR = "GET_ALLOWED_ROUTES_ERROR";

export const PATCH_EDIT_ROLE_APIS = "/system/role-api-allocation";
export const GET_RBAC_ALLOWED_APIS = "/system/allocated-apis";
export const GET_RBAC_ALLOWED_APIS_SUCCESS = "GET_RBAC_ALLOWED_APIS_SUCCESS";
export const GET_RBAC_ALLOWED_APIS_ERROR = "GET_RBAC_ALLOWED_APIS_ERROR";

export const GET_ROLE_ALLOWED_APIS_SUCCESS = "GET_ROLE_ALLOWED_APIS_SUCCESS";
export const GET_ROLE_ALLOWED_APIS_ERROR = "GET_ROLE_ALLOWED_APIS_ERROR";

export const GET_RBAC_POSSIBLE_APIS = "/system/all-apis";
export const GET_RBAC_POSSIBLE_APIS_SUCCESS = "GET_RBAC_POSSIBLE_APIS_SUCCESS";
export const GET_RBAC_POSSIBLE_APIS_ERROR = "GET_RBAC_POSSIBLE_APIS_ERROR";

export const GET_INTERNAL_USER_ROLES = "/internal-users/roles";
export const GET_INTERNAL_USER_ROLES_SUCCESS = "GET_INTERNAL_USER_ROLES_SUCCESS";
export const GET_INTERNAL_USER_ROLES_ERROR = "GET_INTERNAL_USER_ROLES_ERROR";

export const DELETE_INTERVIEWER = "/counselor/interviewer";
export const DELETE_INTERVIEWER_SUCCESS = "DELETE_INTERVIEWER_SUCCESS";
export const DELETE_INTERVIEWER_ERROR = "DELETE_INTERVIEWER_ERROR";

export const COUNSELLOR_PERFORMANCE = "/counselor/counselor-performance";
export const COUNSELLOR_PERFORMANCE_SUCCESS = "COUNSELLOR_PERFORMANCE_SUCCESS";
export const COUNSELLOR_PERFORMANCE_ERROR = "COUNSELLOR_PERFORMANCE_ERROR";
export const CREATE_ROLE = "/internal-users/create-role-and-map-routes"

export const COUNSELOR_CAREER_SUCCESSION_PLAN = "/counselor/career-succession-plan";
export const COUNSELOR_CAREER_SUCCESSION_PLAN_SUCCESS = "COUNSELOR_CAREER_SUCCESSION_PLAN_SUCCESS";
export const COUNSELOR_CAREER_SUCCESSION_PLAN_ERROR = "COUNSELOR_CAREER_SUCCESSION_PLAN_ERROR";

export const GET_ALL_POSSIBLE_ROUTES = "/internal-users/routes/all-possible";
export const GET_ALL_POSSIBLE_ROUTES_SUCCESS = "GET_ALL_POSSIBLE_ROUTES_SUCCESS";
export const GET_ALL_POSSIBLE_ROUTES_ERROR = "GET_ALL_POSSIBLE_ROUTES_ERROR";

export const GET_CSMP_URL = "/counselor/career-success-plan/"
export const GET_CSMP_SUCCESS = "GET_CSMP_SUCCESS"
export const GET_CSMP_ERROR = "GET_CSMP_ERROR"

export const GET_PARTICULAR_ROUTES = "/internal-users/role";
export const GET_PARTICULAR_ROUTES_SUCCESS = "GET_PARTICULAR_ROUTES_SUCCESS";
export const GET_PARTICULAR_ROUTES_ERROR = "GET_PARTICULAR_ROUTES_ERROR";

export const PATCH_EDIT_EXISTING_ROUTES = "/internal-users/edit-role-and-map-routes";
export const PATCH_EDIT_EXISTING_ROUTES_SUCCESS = "PATCH_EDIT_EXISTING_ROUTES_SUCCESS";
export const PATCH_EDIT_EXISTING_ROUTES_ERROR = "PATCH_EDIT_EXISTING_ROUTES_ERROR";

export const COUNSELOR_LEARNERS_DETAIL = "/counselor/learners-detail";
export const COUNSELOR_LEARNERS_DETAIL_SUCCESS = "COUNSELOR_LEARNERS_DETAIL_SUCCESS";
export const COUNSELOR_LEARNERS_DETAIL_ERROR = "COUNSELOR_LEARNERS_DETAIL_ERROR";

export const GET_PERSONIFY_CSP = "/counselor/learner-previous-csp";
export const GET_PERSONIFY_CSP_SUCCESS = "GET_PERSONIFY_CSP_SUCCESS";
export const GET_PERSONIFY_CSP_ERROR = "GET_PERSONIFY_CSP_ERROR";

export const GET_ONBOARDING_STATUS_TRAINING_COUNT = "/counselor/onboarding-status-traningCount";
export const GET_ONBOARDING_STATUS_TRAINING_COUNT_SUCCESS = "GET_ONBOARDING_STATUS_TRAINING_COUNT_SUCCESS";
export const GET_ONBOARDING_STATUS_TRAINING_COUNT_ERROR = "GET_ONBOARDING_STATUS_TRAINING_COUNT_ERROR";

export const GET_ONBOARDING_STATUS_REMAINING_COUNT = "/counselor/onboarding-status-remaincount ";
export const GET_ONBOARDING_STATUS_REMAINING_COUNT_SUCCESS = "GET_ONBOARDING_STATUS_REMAINING_COUNT_SUCCESS";
export const GET_ONBOARDING_STATUS_REMAINING_COUNT_ERROR = "GET_ONBOARDING_STATUS_REMAINING_COUNT";

export const GET_COUNSELLOR_OVERVIEW = "/counselor/overview";
export const GET_COUNSELLOR_OVERVIEW_DATA_SUCCESS = "GET_COUNSELLOR_OVERVIEW_DATA_SUCCESS";
export const GET_COUNSELLOR_OVERVIEW_DATA_ERROR = "GET_COUNSELLOR_OVERVIEW_DATA_ERROR"

export const GET_LOGISTIC_LIST = "/logistic";
export const GET_LOGISTIC_LIST_SUCCESS = "GET_LOGISTIC_LIST_SUCCESS";
export const GET_LOGISTIC_LIST_ERROR = "GET_LOGISTIC_LIST_ERROR";

export const POST_LOGISTIC_GENERATE_NUMBER = "/logistic/generate-number";

export const GET_LOGISTIC_DETAIL = "/logistic";
export const GET_LOGISTIC_DETAIL_SUCCESS = "GET_LOGISTIC_DETAIL_SUCCESS";
export const GET_LOGISTIC_DETAIL_ERROR = "GET_LOGISTIC_DETAIL_ERROR";

export const UPDATE_PRINT_CARD_STATUS = "/logistic";

export const UPDATE_ENTITY_ANALYTICS_STATUS = "/entities/toggelAnalytics";

export const REGION_DATA = "/master/region";
export const GET_REGION_LIST_SUCCESS = "GET_REGION_LIST_SUCCESS";
export const GET_REGION_LIST_ERROR = "GET_REGION_LIST_ERROR";

export const CITY_DATA = "/master/city";
export const GET_CITY_LIST_SUCCESS = "GET_CITY_LIST_SUCCESS";
export const GET_CITY_LIST_ERROR = "GET_CITY_LIST_ERROR";

export const VPA_DATA = "/master/vpa";
export const GET_VPA_LIST_SUCCESS = "GET_VPA_LIST_SUCCESS";
export const GET_VPA_LIST_ERROR = "GET_VPA_LIST_ERROR";

export const OFFER_DATA = "/master/coupon";
export const GET_OFFER_LIST_SUCCESS = "GET_OFFER_LIST_SUCCESS";
export const GET_OFFER_LIST_ERROR = "GET_OFFER_LIST_ERROR";

export const GET_GLOBAL_COUPON = "/global/coupons";
export const GET_GLOBAL_COUPON_SUCCESS = "GET_GLOBAL_COUPON_SUCCESS";
export const GET_GLOBAL_COUPON_ERROR = "GET_GLOBAL_COUPON_ERROR";

export const GET_INVENTORY_URL = "/global/inventory"
export const GET_INVENTORY_LIST = "GET_INVENTORY_LIST"

export const INDIVIDUAL_REGISTER = "/account/buyer-register-with-login";
export const POST_INDIVIDUAL_REGISTER_SUCCESS = "POST_INDIVIDUAL_REGISTER_SUCCESS";
export const POST_INDIVIDUAL_REGISTER_ERROR = "POST_INDIVIDUAL_REGISTER_ERROR";

export const OTP_REGISTER = "/account/verify-otp";
export const POST_OTP_REGISTER_SUCCESS = "POST_OTP_REGISTER_SUCCESS";
export const POST_OTP_REGISTER_ERROR = "POST_OTP_REGISTER_ERROR";

export const GET_SELLER_DASHBOARD = "/global/seller-dashboard";
export const GET_SELLER_DASHBOARD_SUCCESS = "GET_SELLER_DASHBOARD_SUCCESS"
export const GET_SELLER_DASHBOARD_ERROR = "GET_SELLER_DASHBOARD_ERROR"

export const STATE_DATA = "/master/state";
export const GET_STATE_LIST_SUCCESS = "GET_STATE_LIST_SUCCESS";
export const GET_STATE_LIST_ERROR = "GET_STATE_LIST_ERROR";

export const GET_SALSE_TRANSACTION_URL = "/sales/transactions";
export const GET_SALSE_TRANSACTION_LIST = "GET_SALSE_TRANSACTION_LIST";

export const GET_SALES_APP_CUSTOMER_DATA_URL = "/global/pt-offering-type";
export const GET_SALES_APP_CUSTOMER_DATA_SUCCESS = "GET_SALES_APP_CUSTOMER_DATA_SUCCESS";
export const GET_SALES_APP_CUSTOMER_DATA_ERROR = "GET_SALES_APP_CUSTOMER_DATA_ERROR";

export const GET_OFFERING_DETAIL_URL = "/global/pt-offering-type-details/";
export const GET_OFFERING_DETAIL_SUCCESS = "GET_OFFERING_DETAIL_SUCCESS";
export const GET_OFFERING_DETAIL_ERROR = "GET_OFFERING_DETAIL_ERROR";

export const SALES_TRANSACTION = "/sales/transaction";
export const POST_SALES_TRANSACTION_SUCCESS = "POST_SALES_TRANSACTION_SUCCESS";
export const POST_SALES_TRANSACTION_ERROR = "POST_SALES_TRANSACTION_ERROR";

export const GET_COUPON_DETAIL_SUCCESS = "GET_COUPON_DETAIL_SUCCESS";
export const GET_COUPON_DETAIL_ERROR = "GET_COUPON_DETAIL_ERROR";
export const CLEAR_COUPON_DETAIL = "CLEAR_COUPON_DETAIL";

export const GET_TRANSACTION_DETAILS_URL = "/sales/transaction"
export const GET_TRANSACTION_DETAILS = "GET_TRANSACTION_DETAILS"
export const DEPOSIT_SLIP = "/global/deposit-slip";
export const POST_DEPOSIT_SLIP_SUCCESS = "POST_DEPOSIT_SLIP_SUCCESS";
export const POST_DEPOSIT_SLIP_ERROR = "POST_DEPOSIT_SLIP_ERROR";

export const GET_SELLER_DATA = "/master/sellers";
export const GET_SELLER_DATA_SUCCESS = "GET_SELLER_DATA_SUCCESS";
export const GET_SELLER_DATA_ERROR = "GET_SELLER_DATA_ERROR";

export const SELLER_META_DATA = "/master/seller-meta";
export const GET_SELLER_META_DATA_SUCCESS = "GET_SELLER_META_DATA_SUCCESS";
export const GET_SELLER_META_DATA_ERROR = "GET_SELLER_META_DATA_ERROR";

export const GET_UNIQUE_SELLER_META_DATA_SUCCESS = "GET_UNIQUE_SELLER_META_DATA_SUCCESS";
export const GET_UNIQUE_SELLER_META_DATA_ERROR = "GET_UNIQUE_SELLER_META_DATA_ERROR";

export const CHANGE_INVENTORY_STATUS_URL = "/global/inventory";
export const CHANGE_INVENTORY_STATUS_SUCCESS = "CHANGE_INVENTORY_STATUS_SUCCESS";
export const CHANGE_INVENTORY_STATUS_ERROR = "CHANGE_INVENTORY_STATUC_ERROR";

export const GET_USER_VPA_DETAILS_URL = "/global/user-vpa"
export const GET_USER_VPA_DETAILS = "GET_USER_VPA_DETAILS"

export const GET_CARD_VALIDITY_URL = "/global/validate-card";
export const GET_CARD_VALIDITY_SUCCESS = "GET_CARD_VALIDITY_SUCCESS";
export const GET_CARD_VALIDITY_ERROR = "GET_CARD_VALIDITY_ERROR";

export const DISABLE_TRANSACTION_URL = "/sales/transaction/disable"
export const DISABLE_TRANSACTION_SUCCESS = "DISABLE_TRANSACTION_SUCCESS"
export const DISABLE_TRANSACTION_ERROR = "DISABLE_TRANSACTION_ERROR"

export const CARD_ALLOCATION_LIST = "";
export const GET_CARD_ALLOCATION_LIST_SUCCESS = "GET_CARD_ALLOCATION_LIST_SUCCESS";
export const GET_CARD_ALLOCATION_LIST_ERROR = "GET_CARD_ALLOCATION_LIST_ERROR";

export const CARD_LOT = "/master/card-lot";
export const CARD_LOT_SUCCESS = "CARD_LOT_SUCCESS";
export const CARD_LOT_ERROR = "CARD_LOT_ERROR";

export const POST_CARD_ALLOCATION = "/master/card-allocation";

export const GET_MASTER_TRANSACTION = "/master/master-transaction";
export const GET_MASTER_TRANSACTION_SUCCESS = "GET_MASTER_TRANSACTION_SUCCESS";
export const GET_MASTER_TRANSACTION_ERROR = "GET_MASTER_TRANSACTION_ERROR";

export const UPDATE_MASTER_TRANSACTION_STATUS = "/global/deposit-slip";

export const GET_UNIQUE_MASTER_TRANSACTION_SUCCESS = "GET_UNIQUE_MASTER_TRANSACTION_SUCCESS";
export const GET_UNIQUE_MASTER_TRANSACTION_ERROR = "GET_UNIQUE_MASTER_TRANSACTION_ERROR";

export const GET_USER_STATE_LIST = "/sales/states";
export const GET_USER_STATE_LIST_SUCCESS = "GET_USER_STATE_LIST_SUCCESS";
export const GET_USER_STATE_LIST_ERROR = "GET_USER_STATE_LIST_ERROR"

export const GET_MASTERENTITY_API = "/masterentity";
export const GET_MASTERENTITY_SUCCESS = "GET_MASTERENTITY_SUCCESS";
export const GET_MASTERENTITY_ERROR = "GET_MASTERENTITY_ERROR";

// export const DELETE_MASTERENTITY_API = "/masterentity";
// export const CREATE_MASTERENTITY_API = "/masterentity";

export const EXPORT_MASTERENTITY_API = "/masterentity-export";
export const EXPORT_ALL_MASTERENTITY_API = "/masterentity-export-all";
export const IMPORT_MASTERENTITY_API = "/masterentity-import";

// export const DELETE_MASTERENTITY_SUCCESS = "DEL_MASTERENTITY_SUCCESS";
// export const DELETE_MASTERENTITY_ERROR = "DEL_MASTERENTITY_ERROR";

// export const CREATE_MASTERENTITY_SUCCESS = "DEL_MASTERENTITY_SUCCESS";
// export const CREATE_MASTERENTITY_ERROR = "DEL_MASTERENTITY_ERROR";
export const GET_CARD_LOTS = "/master/card-lots";
export const GET_CARD_LOTS_SUCCESS = "GET_CARD_LOTS_SUCCESS";
export const GET_CARD_LOTS_ERROR = "GET_CARD_LOTS_ERROR";

export const GET_PT_OFFERINGS = "/global/pt-offerings";
export const GET_PT_OFFERINGS_SUCCESS = "GET_PT_OFFERINGS_SUCCESS";
export const GET_PT_OFFERINGS_ERROR = "GET_PT_OFFERINGS_ERROR";

export const GET_SERVICES_API = "/services";
export const GET_SERVICES_SUCCESS = "GET_SERVICES_SUCCESS";
export const GET_SERVICES_ERROR = "GET_SERVICES_ERROR";
export const DELETE_SERVICE_API = "/global/service"

export const GET_TESTIMONIAL_API = "/testimonials";
export const DELETE_TESTIMONIAL_API = "/global/testimonial"
export const GET_TESTIMONIAL_SUCCESS = "GET_TESTIMONIAL_SUCCESS";
export const GET_TESTIMONIAL_ERROR = "GET_TESTIMONIAL_ERROR";

export const POST_OFFLINE_SALES = "/sales/offline-sales";

export const UPDATE_EXTERNAL_USER_DATA = "/external-users"

export const GET_BANNER_SECTION_API = "/banner-sections";
export const DELETE_BANNER_SECTION_API = "/global/banner-section"
export const GET_BANNER_SECTION_SUCCESS = "GET_BANNER_SECTION_SUCCESS";
export const GET_BANNER_SECTION_ERROR = "GET_BANNER_SECTION_ERROR";

export const GET_BLOGSVIDEOS_API = "/blogs-videos";
export const GET_BLOGSVIDEOS_SUCCESS = "GET_BLOGSVIDEOS_SUCCESS";
export const GET_BLOGSVIDEOS_ERROR = "GET_BLOGSVIDEOS_ERROR";